/*
 * App URI: 202105/arrayTest
 * Source Location: 202105/arrayTest.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("202105/arrayTest", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * arrayTest.js
			 * Created at 2021. 5. 11. 오후 2:44:01.
			 *
			 * @author HANS
			 ************************************************/
			
			
			
			/*
			 * "Button" 버튼(btn1)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn1 = e.control;
				
				var startTime = moment().valueOf();
				
				
				var allD = app.getAllDataControls();
				
			
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("ds2");
			dataSet_2.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_2);
			
			var dataSet_3 = new cpr.data.DataSet("ds3");
			dataSet_3.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_3);
			
			var dataSet_4 = new cpr.data.DataSet("ds4");
			dataSet_4.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_4);
			
			var dataSet_5 = new cpr.data.DataSet("ds5");
			dataSet_5.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_5);
			
			var dataSet_6 = new cpr.data.DataSet("ds6");
			dataSet_6.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_6);
			
			var dataSet_7 = new cpr.data.DataSet("ds7");
			dataSet_7.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_7);
			
			var dataSet_8 = new cpr.data.DataSet("ds8");
			dataSet_8.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_8);
			
			var dataSet_9 = new cpr.data.DataSet("ds9");
			dataSet_9.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_9);
			
			var dataSet_10 = new cpr.data.DataSet("ds10");
			dataSet_10.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_10);
			
			var dataSet_11 = new cpr.data.DataSet("ds11");
			dataSet_11.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_11);
			
			var dataSet_12 = new cpr.data.DataSet("ds12");
			dataSet_12.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_12);
			
			var dataSet_13 = new cpr.data.DataSet("ds13");
			dataSet_13.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_13);
			
			var dataSet_14 = new cpr.data.DataSet("ds14");
			dataSet_14.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_14);
			
			var dataSet_15 = new cpr.data.DataSet("ds15");
			dataSet_15.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_15);
			
			var dataSet_16 = new cpr.data.DataSet("ds16");
			dataSet_16.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_16);
			
			var dataSet_17 = new cpr.data.DataSet("ds17");
			dataSet_17.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_17);
			
			var dataSet_18 = new cpr.data.DataSet("ds18");
			dataSet_18.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_18);
			
			var dataSet_19 = new cpr.data.DataSet("ds19");
			dataSet_19.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"}
				]
			});
			app.register(dataSet_19);
			var dataMap_1 = new cpr.data.DataMap("dm1");
			dataMap_1.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_1);
			
			var dataMap_2 = new cpr.data.DataMap("dm2");
			dataMap_2.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_2);
			
			var dataMap_3 = new cpr.data.DataMap("dm3");
			dataMap_3.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_3);
			
			var dataMap_4 = new cpr.data.DataMap("dm4");
			dataMap_4.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_4);
			
			var dataMap_5 = new cpr.data.DataMap("dm5");
			dataMap_5.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_5);
			
			var dataMap_6 = new cpr.data.DataMap("dm6");
			dataMap_6.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_6);
			
			var dataMap_7 = new cpr.data.DataMap("dm7");
			dataMap_7.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_7);
			
			var dataMap_8 = new cpr.data.DataMap("dm8");
			dataMap_8.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_8);
			
			var dataMap_9 = new cpr.data.DataMap("dm9");
			dataMap_9.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_9);
			
			var dataMap_10 = new cpr.data.DataMap("dm10");
			dataMap_10.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_10);
			
			var dataMap_11 = new cpr.data.DataMap("dm11");
			dataMap_11.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_11);
			
			var dataMap_12 = new cpr.data.DataMap("dm12");
			dataMap_12.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_12);
			
			var dataMap_13 = new cpr.data.DataMap("dm13");
			dataMap_13.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_13);
			
			var dataMap_14 = new cpr.data.DataMap("dm14");
			dataMap_14.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_14);
			
			var dataMap_15 = new cpr.data.DataMap("dm15");
			dataMap_15.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_15);
			
			var dataMap_16 = new cpr.data.DataMap("dm16");
			dataMap_16.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_16);
			
			var dataMap_17 = new cpr.data.DataMap("dm17");
			dataMap_17.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_17);
			
			var dataMap_18 = new cpr.data.DataMap("dm18");
			dataMap_18.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_18);
			
			var dataMap_19 = new cpr.data.DataMap("dm19");
			dataMap_19.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_19);
			
			var dataMap_20 = new cpr.data.DataMap("dm20");
			dataMap_20.parseData({
				"columns" : [
					{
						"name": "column1",
						"defaultValue": "a"
					},
					{
						"name": "column2",
						"defaultValue": "b"
					},
					{
						"name": "column3",
						"defaultValue": "c"
					},
					{
						"name": "column4",
						"defaultValue": "d"
					},
					{
						"name": "column5",
						"defaultValue": "e"
					}
				]
			});
			app.register(dataMap_20);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button("btn1");
			button_1.value = "Button";
			if(typeof onBtn1Click == "function") {
				button_1.addEventListener("click", onBtn1Click);
			}
			container.addChild(button_1, {
				"top": "20px",
				"left": "20px",
				"width": "100px",
				"height": "20px"
			});
		}
	});
	app.title = "arrayTest";
	cpr.core.Platform.INSTANCE.register(app);
})();
