/*
 * App URI: 202106/P00004
 * Source Location: 202106/P00004.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("202106/P00004", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * P00004.js
			 * Created at 2021. 6. 28. 오후 1:41:00.
			 *
			 * @author ryu
			 ************************************************/;
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "column1"},
					{"name": "column2"}
				],
				"rows": [
					{"column1": "계좌목록", "column2": "거래내역"},
					{"column1": "고객정보", "column2": "상세정보"}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (max-width: 1023px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["P00004"]);
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.spacing = 0;
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grp1");
			// Layout
			var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
			flowLayout_1.horizontalSpacing = 0;
			flowLayout_1.verticalSpacing = 30;
			flowLayout_1.verticalAlign = "middle";
			flowLayout_1.leftMargin = 30;
			flowLayout_1.rightMargin = 30;
			flowLayout_1.topMargin = 30;
			flowLayout_1.bottomMargin = 30;
			group_1.setLayout(flowLayout_1);
			(function(container){
				var output_1 = new cpr.controls.Output("opt1");
				output_1.value = "현대차증권의 ";
				container.addChild(output_1, {
					"autoSize": "both",
					"width": "100px",
					"height": "20px"
				});
				var output_2 = new cpr.controls.Output("opt2");
				output_2.value = "개인신용정보";
				container.addChild(output_2, {
					"autoSize": "both",
					"width": "100px",
					"height": "20px"
				});
				var output_3 = new cpr.controls.Output("opt3");
				output_3.value = "가";
				container.addChild(output_3, {
					"autoSize": "both",
					"width": "100px",
					"height": "20px"
				});
				var comboBox_1 = new cpr.controls.ComboBox("cmb1");
				(function(comboBox_1){
				})(comboBox_1);
				container.addChild(comboBox_1, {
					"width": "72px",
					"height": "40px"
				});
				var output_4 = new cpr.controls.Output("opt4");
				output_4.value = "동안";
				container.addChild(output_4, {
					"autoSize": "both",
					"width": "52px",
					"height": "20px",
					"minWidth": 52
				});
				var comboBox_2 = new cpr.controls.ComboBox("cmb2");
				(function(comboBox_2){
				})(comboBox_2);
				container.addChild(comboBox_2, {
					"autoSize": "none",
					"width": "97px",
					"height": "40px"
				});
				var output_5 = new cpr.controls.Output("opt5");
				output_5.value = "으로";
				container.addChild(output_5, {
					"autoSize": "both",
					"width": "52px",
					"height": "20px"
				});
				var output_6 = new cpr.controls.Output("opt6");
				output_6.value = "사업자 A에게 제공";
				container.addChild(output_6, {
					"autoSize": "both",
					"width": "180px",
					"height": "20px"
				});
				var output_7 = new cpr.controls.Output("opt7");
				output_7.value = "되며";
				container.addChild(output_7, {
					"autoSize": "both",
					"width": "100px",
					"height": "20px"
				});
				var comboBox_3 = new cpr.controls.ComboBox("cmb3");
				(function(comboBox_3){
				})(comboBox_3);
				container.addChild(comboBox_3, {
					"width": "72px",
					"height": "40px"
				});
				var output_8 = new cpr.controls.Output("opt8");
				output_8.value = "동안 정보를 보관하게 됩니다.";
				container.addChild(output_8, {
					"autoSize": "both",
					"width": "199px",
					"height": "20px"
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "343px",
				"height": "410px"
			});
		}
	});
	app.title = "전송요구 내역 확인";
	cpr.core.Platform.INSTANCE.register(app);
})();
