/*
 * App URI: 202101/helper
 * Source Location: 202101/helper.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("202101/helper", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * helper.js
			 * Created at 2021. 1. 21. 오후 3:20:56.
			 *
			 * @author HANS
			 ************************************************/
			
			
			var start = null;
			/*
			 * "Button" 버튼(btn3)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn3Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn3 = e.control;
				start = moment().valueOf();
				
				var indx = app.lookup("nbe1").numberValue;
				var vaData = []
				for(var i = 0 ; i < indx ; i++) {
					
					var voRow = {
						"column1" :"aaaaaaaa",
						"column2" :"aaaaaaaa",
						"column3" :"aaaaaaaa",
						"column4" :"aaaaaaaa",
						"column5" :"aaaaaaaa",
						"column6" :"aaaaaaaa",
						"column7" :"aaaaaaaa",
						"column8" :"aaaaaaaa",
						"column9" :"aaaaaaaa",
						"column10" :"aaaaaaaa",
						"column11" :"aaaaaaaa",
						"column12" :"aaaaaaaa",
						"column13" :"aaaaaaaa",
						"column14" :"aaaaaaaa",
						"column15" :"aaaaaaaa",
						"column16" :"aaaaaaaa",
						"column17" :"aaaaaaaa",
						"column18" :"aaaaaaaa",
						"column19" :"aaaaaaaa",
						"column20" :"aaaaaaaa",
						"column21" :"aaaaaaaa",
						"column22" :"aaaaaaaa",
						"column23" :"aaaaaaaa",
						"column24" :"aaaaaaaa",
						"column25" :"aaaaaaaa",
						"column26" :"aaaaaaaa",
						"column27" :"aaaaaaaa",
						"column28" :"aaaaaaaa",
						"column29" :"aaaaaaaa",
						"column30" :"aaaaaaaa",
						"column31" :"aaaaaaaa",
						"column32" :"aaaaaaaa",
						"column33" :"aaaaaaaa",
						"column34" :"aaaaaaaa",
						"column35" :"aaaaaaaa",
						"column36" :"aaaaaaaa",
						"column37" :"aaaaaaaa",
						"column38" :"aaaaaaaa",
						"column39" :"aaaaaaaa",
						"column40" :"aaaaaaaa",
						"column41" :"aaaaaaaa",
						"column42" :"aaaaaaaa",
						"column43" :"aaaaaaaa",
						"column44" :"aaaaaaaa",
						"column45" :"aaaaaaaa",
						"column46" :"aaaaaaaa",
						"column47" :"aaaaaaaa",
						"column48" :"aaaaaaaa",
						"column49" :"aaaaaaaa",
						"column50" :"aaaaaaaa",
						"column51" :"aaaaaaaa",
						"column52" :"aaaaaaaa",
						"column53" :"aaaaaaaa",
						"column54" :"aaaaaaaa",
						"column55" :"aaaaaaaa",
						"column56" :"aaaaaaaa",
						"column57" :"aaaaaaaa",
						"column58" :"aaaaaaaa",
						"column59" :"aaaaaaaa",
						"column60" :"aaaaaaaa",
						"column61" :"aaaaaaaa",
						"column62" :"aaaaaaaa",
						"column63" :"aaaaaaaa",
						"column64" :"aaaaaaaa",
						"column65" :"aaaaaaaa",
						"column66" :"aaaaaaaa",
						"column67" :"aaaaaaaa",
						"column68" :"aaaaaaaa",
						"column69" :"aaaaaaaa",
						"column70" :"aaaaaaaa",
						"column71" :"aaaaaaaa",
						"column72" :"aaaaaaaa",
						"column73" :"aaaaaaaa",
						"column74" :"aaaaaaaa",
						"column75" :"aaaaaaaa",
						"column76" :"aaaaaaaa",
						"column77" :"aaaaaaaa",
						"column78" :"aaaaaaaa",
						"column79" :"aaaaaaaa",
						"column80" :"aaaaaaaa",
						"column81" :"aaaaaaaa",
						"column82" :"aaaaaaaa",
						"column83" :"aaaaaaaa",
						"column84" :"aaaaaaaa",
						"column85" :"aaaaaaaa",
						"column86" :"aaaaaaaa",
						"column87" :"aaaaaaaa",
						"column88" :"aaaaaaaa",
						"column89" :"aaaaaaaa",
						"column90" :"aaaaaaaa",
						"column91" :"aaaaaaaa",
						"column92" :"aaaaaaaa",
						"column93" :"aaaaaaaa",
						"column94" :"aaaaaaaa",
						"column95" :"aaaaaaaa",
						"column96" :"aaaaaaaa",
						"column97" :"aaaaaaaa",
						"column98" :"aaaaaaaa",
						"column99" :"aaaaaaaa",
						"column100" :"aaaaaaaa"
						
						
					};
					
					vaData.push(voRow);
				}
				start = moment().valueOf();
				app.lookup("dsList").build(vaData);
				console.log("BUILD DONE");
				console.log(moment.duration(moment().valueOf()-start)/1);
			}
			
			
			
			var now = null;
			/*
			 * "Button" 버튼(btn4)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn4Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn4 = e.control;
				
				var grd = app.lookup("grd2");
				
				var initC = grd.getInitConfig();
				initC.dataSet = app.lookup("dsList");
				
				now = moment().valueOf();
				grd.init(initC);
				grd.insertRow(0, true);
			}
			
			
			/*
			 * 그리드에서 insert 이벤트 발생 시 호출.
			 * Grid의 행이 추가되었을 때 이벤트.
			 */
			function onGrd2Insert(/* cpr.events.CGridEvent */ e){
				/** 
				 * @type cpr.controls.Grid
				 */
				var grd2 = e.control;
				console.log("INIT AND INSERTED!");
				console.log(moment.duration(moment().valueOf()-now)/1);
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("dsList");
			dataSet_1.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"},
					{"name": "column9"},
					{"name": "column10"},
					{"name": "column11"},
					{"name": "column12"},
					{"name": "column13"},
					{"name": "column14"},
					{"name": "column15"},
					{"name": "column16"},
					{"name": "column17"},
					{"name": "column18"},
					{"name": "column19"},
					{"name": "column20"},
					{"name": "column21"},
					{"name": "column22"},
					{"name": "column23"},
					{"name": "column24"},
					{"name": "column25"},
					{"name": "column26"},
					{"name": "column27"},
					{"name": "column28"},
					{"name": "column29"},
					{"name": "column30"},
					{"name": "column31"},
					{"name": "column32"},
					{"name": "column33"},
					{"name": "column34"},
					{"name": "column35"},
					{"name": "column36"},
					{"name": "column37"},
					{"name": "column38"},
					{"name": "column39"},
					{"name": "column40"},
					{"name": "column41"},
					{"name": "column42"},
					{"name": "column43"},
					{"name": "column44"},
					{"name": "column45"},
					{"name": "column46"},
					{"name": "column47"},
					{"name": "column48"},
					{"name": "column49"},
					{"name": "column50"},
					{"name": "column51"},
					{"name": "column52"},
					{"name": "column53"},
					{"name": "column54"},
					{"name": "column55"},
					{"name": "column56"},
					{"name": "column57"},
					{"name": "column58"},
					{"name": "column59"},
					{"name": "column60"},
					{"name": "column61"},
					{"name": "column62"},
					{"name": "column63"},
					{"name": "column64"},
					{"name": "column65"},
					{"name": "column66"},
					{"name": "column67"},
					{"name": "column68"},
					{"name": "column69"},
					{"name": "column70"},
					{"name": "column71"},
					{"name": "column72"},
					{"name": "column73"},
					{"name": "column74"},
					{"name": "column75"},
					{"name": "column76"},
					{"name": "column77"},
					{"name": "column78"},
					{"name": "column79"},
					{"name": "column80"},
					{"name": "column81"},
					{"name": "column82"},
					{"name": "column83"},
					{"name": "column84"},
					{"name": "column85"},
					{"name": "column86"},
					{"name": "column87"},
					{"name": "column88"},
					{"name": "column89"},
					{"name": "column90"},
					{"name": "column91"},
					{"name": "column92"},
					{"name": "column93"},
					{"name": "column94"},
					{"name": "column95"},
					{"name": "column96"},
					{"name": "column97"},
					{"name": "column98"},
					{"name": "column99"},
					{"name": "column100"}
				]
			});
			if(typeof onDsListLoad == "function") {
				dataSet_1.addEventListener("load", onDsListLoad);
			}
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("dsList2");
			dataSet_2.parseData({
				"columns" : [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"},
					{"name": "column4"},
					{"name": "column5"},
					{"name": "column6"},
					{"name": "column7"},
					{"name": "column8"},
					{"name": "column9"},
					{"name": "column10"},
					{"name": "column11"},
					{"name": "column12"},
					{"name": "column13"},
					{"name": "column14"},
					{"name": "column15"},
					{"name": "column16"},
					{"name": "column17"},
					{"name": "column18"},
					{"name": "column19"},
					{"name": "column20"},
					{"name": "column21"},
					{"name": "column22"},
					{"name": "column23"},
					{"name": "column24"},
					{"name": "column25"},
					{"name": "column26"},
					{"name": "column27"},
					{"name": "column28"},
					{"name": "column29"},
					{"name": "column30"},
					{"name": "column31"},
					{"name": "column32"},
					{"name": "column33"},
					{"name": "column34"},
					{"name": "column35"},
					{"name": "column36"},
					{"name": "column37"},
					{"name": "column38"},
					{"name": "column39"},
					{"name": "column40"},
					{"name": "column41"},
					{"name": "column42"},
					{"name": "column43"},
					{"name": "column44"},
					{"name": "column45"},
					{"name": "column46"},
					{"name": "column47"},
					{"name": "column48"},
					{"name": "column49"},
					{"name": "column50"},
					{"name": "column51"},
					{"name": "column52"},
					{"name": "column53"},
					{"name": "column54"},
					{"name": "column55"},
					{"name": "column56"},
					{"name": "column57"},
					{"name": "column58"},
					{"name": "column59"},
					{"name": "column60"},
					{"name": "column61"},
					{"name": "column62"},
					{"name": "column63"},
					{"name": "column64"},
					{"name": "column65"},
					{"name": "column66"},
					{"name": "column67"},
					{"name": "column68"},
					{"name": "column69"},
					{"name": "column70"},
					{"name": "column71"},
					{"name": "column72"},
					{"name": "column73"},
					{"name": "column74"},
					{"name": "column75"},
					{"name": "column76"},
					{"name": "column77"},
					{"name": "column78"},
					{"name": "column79"},
					{"name": "column80"},
					{"name": "column81"},
					{"name": "column82"},
					{"name": "column83"},
					{"name": "column84"},
					{"name": "column85"},
					{"name": "column86"},
					{"name": "column87"},
					{"name": "column88"},
					{"name": "column89"},
					{"name": "column90"},
					{"name": "column91"},
					{"name": "column92"},
					{"name": "column93"},
					{"name": "column94"},
					{"name": "column95"},
					{"name": "column96"},
					{"name": "column97"},
					{"name": "column98"},
					{"name": "column99"},
					{"name": "column100"}
				]
			});
			app.register(dataSet_2);
			var submission_1 = new cpr.protocols.Submission("sms1");
			submission_1.action = "dataMan/massData.json";
			submission_1.addResponseData(dataSet_1, false);
			if(typeof onSms1SubmitSuccess == "function") {
				submission_1.addEventListener("submit-success", onSms1SubmitSuccess);
			}
			app.register(submission_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var grid_1 = new cpr.controls.Grid("grd2");
			grid_1.init({
				"dataSet": app.lookup("dsList2"),
				"columns": [
					{"width": "50px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.filterable = false;
								cell.sortable = false;
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.targetColumnName = "column1";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column1";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.targetColumnName = "column2";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column2";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.targetColumnName = "column3";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column3";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.targetColumnName = "column4";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column4";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.targetColumnName = "column5";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column5";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.targetColumnName = "column6";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column6";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
								cell.targetColumnName = "column7";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column7";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 8},
							"configurator": function(cell){
								cell.targetColumnName = "column8";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column8";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 9},
							"configurator": function(cell){
								cell.targetColumnName = "column9";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column9";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 10},
							"configurator": function(cell){
								cell.targetColumnName = "column10";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column10";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 11},
							"configurator": function(cell){
								cell.targetColumnName = "column11";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column11";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 12},
							"configurator": function(cell){
								cell.targetColumnName = "column12";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column12";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 13},
							"configurator": function(cell){
								cell.targetColumnName = "column13";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column13";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 14},
							"configurator": function(cell){
								cell.targetColumnName = "column14";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column14";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 15},
							"configurator": function(cell){
								cell.targetColumnName = "column15";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column15";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 16},
							"configurator": function(cell){
								cell.targetColumnName = "column16";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column16";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 17},
							"configurator": function(cell){
								cell.targetColumnName = "column17";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column17";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 18},
							"configurator": function(cell){
								cell.targetColumnName = "column18";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column18";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 19},
							"configurator": function(cell){
								cell.targetColumnName = "column19";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column19";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 20},
							"configurator": function(cell){
								cell.targetColumnName = "column20";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column20";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 21},
							"configurator": function(cell){
								cell.targetColumnName = "column21";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column21";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 22},
							"configurator": function(cell){
								cell.targetColumnName = "column22";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column22";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 23},
							"configurator": function(cell){
								cell.targetColumnName = "column23";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column23";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 24},
							"configurator": function(cell){
								cell.targetColumnName = "column24";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column24";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 25},
							"configurator": function(cell){
								cell.targetColumnName = "column25";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column25";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 26},
							"configurator": function(cell){
								cell.targetColumnName = "column26";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column26";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 27},
							"configurator": function(cell){
								cell.targetColumnName = "column27";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column27";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 28},
							"configurator": function(cell){
								cell.targetColumnName = "column28";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column28";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 29},
							"configurator": function(cell){
								cell.targetColumnName = "column29";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column29";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 30},
							"configurator": function(cell){
								cell.targetColumnName = "column30";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column30";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 31},
							"configurator": function(cell){
								cell.targetColumnName = "column31";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column31";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 32},
							"configurator": function(cell){
								cell.targetColumnName = "column32";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column32";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 33},
							"configurator": function(cell){
								cell.targetColumnName = "column33";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column33";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 34},
							"configurator": function(cell){
								cell.targetColumnName = "column34";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column34";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 35},
							"configurator": function(cell){
								cell.targetColumnName = "column35";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column35";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 36},
							"configurator": function(cell){
								cell.targetColumnName = "column36";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column36";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 37},
							"configurator": function(cell){
								cell.targetColumnName = "column37";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column37";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 38},
							"configurator": function(cell){
								cell.targetColumnName = "column38";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column38";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 39},
							"configurator": function(cell){
								cell.targetColumnName = "column39";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column39";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 40},
							"configurator": function(cell){
								cell.targetColumnName = "column40";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column40";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 41},
							"configurator": function(cell){
								cell.targetColumnName = "column41";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column41";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 42},
							"configurator": function(cell){
								cell.targetColumnName = "column42";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column42";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 43},
							"configurator": function(cell){
								cell.targetColumnName = "column43";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column43";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 44},
							"configurator": function(cell){
								cell.targetColumnName = "column44";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column44";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 45},
							"configurator": function(cell){
								cell.targetColumnName = "column45";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column45";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 46},
							"configurator": function(cell){
								cell.targetColumnName = "column46";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column46";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 47},
							"configurator": function(cell){
								cell.targetColumnName = "column47";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column47";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 48},
							"configurator": function(cell){
								cell.targetColumnName = "column48";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column48";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 49},
							"configurator": function(cell){
								cell.targetColumnName = "column49";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column49";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 50},
							"configurator": function(cell){
								cell.targetColumnName = "column50";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column50";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 51},
							"configurator": function(cell){
								cell.targetColumnName = "column51";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column51";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 52},
							"configurator": function(cell){
								cell.targetColumnName = "column52";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column52";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 53},
							"configurator": function(cell){
								cell.targetColumnName = "column53";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column53";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 54},
							"configurator": function(cell){
								cell.targetColumnName = "column54";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column54";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 55},
							"configurator": function(cell){
								cell.targetColumnName = "column55";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column55";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 56},
							"configurator": function(cell){
								cell.targetColumnName = "column56";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column56";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 57},
							"configurator": function(cell){
								cell.targetColumnName = "column57";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column57";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 58},
							"configurator": function(cell){
								cell.targetColumnName = "column58";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column58";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 59},
							"configurator": function(cell){
								cell.targetColumnName = "column59";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column59";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 60},
							"configurator": function(cell){
								cell.targetColumnName = "column60";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column60";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 61},
							"configurator": function(cell){
								cell.targetColumnName = "column61";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column61";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 62},
							"configurator": function(cell){
								cell.targetColumnName = "column62";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column62";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 63},
							"configurator": function(cell){
								cell.targetColumnName = "column63";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column63";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 64},
							"configurator": function(cell){
								cell.targetColumnName = "column64";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column64";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 65},
							"configurator": function(cell){
								cell.targetColumnName = "column65";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column65";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 66},
							"configurator": function(cell){
								cell.targetColumnName = "column66";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column66";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 67},
							"configurator": function(cell){
								cell.targetColumnName = "column67";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column67";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 68},
							"configurator": function(cell){
								cell.targetColumnName = "column68";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column68";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 69},
							"configurator": function(cell){
								cell.targetColumnName = "column69";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column69";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 70},
							"configurator": function(cell){
								cell.targetColumnName = "column70";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column70";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 71},
							"configurator": function(cell){
								cell.targetColumnName = "column71";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column71";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 72},
							"configurator": function(cell){
								cell.targetColumnName = "column72";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column72";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 73},
							"configurator": function(cell){
								cell.targetColumnName = "column73";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column73";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 74},
							"configurator": function(cell){
								cell.targetColumnName = "column74";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column74";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 75},
							"configurator": function(cell){
								cell.targetColumnName = "column75";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column75";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 76},
							"configurator": function(cell){
								cell.targetColumnName = "column76";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column76";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 77},
							"configurator": function(cell){
								cell.targetColumnName = "column77";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column77";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 78},
							"configurator": function(cell){
								cell.targetColumnName = "column78";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column78";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 79},
							"configurator": function(cell){
								cell.targetColumnName = "column79";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column79";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 80},
							"configurator": function(cell){
								cell.targetColumnName = "column80";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column80";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 81},
							"configurator": function(cell){
								cell.targetColumnName = "column81";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column81";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 82},
							"configurator": function(cell){
								cell.targetColumnName = "column82";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column82";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 83},
							"configurator": function(cell){
								cell.targetColumnName = "column83";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column83";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 84},
							"configurator": function(cell){
								cell.targetColumnName = "column84";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column84";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 85},
							"configurator": function(cell){
								cell.targetColumnName = "column85";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column85";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 86},
							"configurator": function(cell){
								cell.targetColumnName = "column86";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column86";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 87},
							"configurator": function(cell){
								cell.targetColumnName = "column87";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column87";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 88},
							"configurator": function(cell){
								cell.targetColumnName = "column88";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column88";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 89},
							"configurator": function(cell){
								cell.targetColumnName = "column89";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column89";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 90},
							"configurator": function(cell){
								cell.targetColumnName = "column90";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column90";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 91},
							"configurator": function(cell){
								cell.targetColumnName = "column91";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column91";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 92},
							"configurator": function(cell){
								cell.targetColumnName = "column92";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column92";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 93},
							"configurator": function(cell){
								cell.targetColumnName = "column93";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column93";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 94},
							"configurator": function(cell){
								cell.targetColumnName = "column94";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column94";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 95},
							"configurator": function(cell){
								cell.targetColumnName = "column95";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column95";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 96},
							"configurator": function(cell){
								cell.targetColumnName = "column96";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column96";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 97},
							"configurator": function(cell){
								cell.targetColumnName = "column97";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column97";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 98},
							"configurator": function(cell){
								cell.targetColumnName = "column98";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column98";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 99},
							"configurator": function(cell){
								cell.targetColumnName = "column99";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column99";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 100},
							"configurator": function(cell){
								cell.targetColumnName = "column100";
								cell.filterable = false;
								cell.sortable = false;
								cell.text = "column100";
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.columnType = "rowindex";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnName = "column1";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.columnName = "column2";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 3},
							"configurator": function(cell){
								cell.columnName = "column3";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 4},
							"configurator": function(cell){
								cell.columnName = "column4";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 5},
							"configurator": function(cell){
								cell.columnName = "column5";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 6},
							"configurator": function(cell){
								cell.columnName = "column6";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 7},
							"configurator": function(cell){
								cell.columnName = "column7";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 8},
							"configurator": function(cell){
								cell.columnName = "column8";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 9},
							"configurator": function(cell){
								cell.columnName = "column9";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 10},
							"configurator": function(cell){
								cell.columnName = "column10";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 11},
							"configurator": function(cell){
								cell.columnName = "column11";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 12},
							"configurator": function(cell){
								cell.columnName = "column12";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 13},
							"configurator": function(cell){
								cell.columnName = "column13";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 14},
							"configurator": function(cell){
								cell.columnName = "column14";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 15},
							"configurator": function(cell){
								cell.columnName = "column15";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 16},
							"configurator": function(cell){
								cell.columnName = "column16";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 17},
							"configurator": function(cell){
								cell.columnName = "column17";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 18},
							"configurator": function(cell){
								cell.columnName = "column18";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 19},
							"configurator": function(cell){
								cell.columnName = "column19";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 20},
							"configurator": function(cell){
								cell.columnName = "column20";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 21},
							"configurator": function(cell){
								cell.columnName = "column21";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 22},
							"configurator": function(cell){
								cell.columnName = "column22";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 23},
							"configurator": function(cell){
								cell.columnName = "column23";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 24},
							"configurator": function(cell){
								cell.columnName = "column24";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 25},
							"configurator": function(cell){
								cell.columnName = "column25";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 26},
							"configurator": function(cell){
								cell.columnName = "column26";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 27},
							"configurator": function(cell){
								cell.columnName = "column27";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 28},
							"configurator": function(cell){
								cell.columnName = "column28";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 29},
							"configurator": function(cell){
								cell.columnName = "column29";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 30},
							"configurator": function(cell){
								cell.columnName = "column30";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 31},
							"configurator": function(cell){
								cell.columnName = "column31";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 32},
							"configurator": function(cell){
								cell.columnName = "column32";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 33},
							"configurator": function(cell){
								cell.columnName = "column33";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 34},
							"configurator": function(cell){
								cell.columnName = "column34";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 35},
							"configurator": function(cell){
								cell.columnName = "column35";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 36},
							"configurator": function(cell){
								cell.columnName = "column36";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 37},
							"configurator": function(cell){
								cell.columnName = "column37";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 38},
							"configurator": function(cell){
								cell.columnName = "column38";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 39},
							"configurator": function(cell){
								cell.columnName = "column39";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 40},
							"configurator": function(cell){
								cell.columnName = "column40";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 41},
							"configurator": function(cell){
								cell.columnName = "column41";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 42},
							"configurator": function(cell){
								cell.columnName = "column42";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 43},
							"configurator": function(cell){
								cell.columnName = "column43";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 44},
							"configurator": function(cell){
								cell.columnName = "column44";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 45},
							"configurator": function(cell){
								cell.columnName = "column45";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 46},
							"configurator": function(cell){
								cell.columnName = "column46";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 47},
							"configurator": function(cell){
								cell.columnName = "column47";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 48},
							"configurator": function(cell){
								cell.columnName = "column48";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 49},
							"configurator": function(cell){
								cell.columnName = "column49";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 50},
							"configurator": function(cell){
								cell.columnName = "column50";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 51},
							"configurator": function(cell){
								cell.columnName = "column51";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 52},
							"configurator": function(cell){
								cell.columnName = "column52";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 53},
							"configurator": function(cell){
								cell.columnName = "column53";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 54},
							"configurator": function(cell){
								cell.columnName = "column54";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 55},
							"configurator": function(cell){
								cell.columnName = "column55";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 56},
							"configurator": function(cell){
								cell.columnName = "column56";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 57},
							"configurator": function(cell){
								cell.columnName = "column57";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 58},
							"configurator": function(cell){
								cell.columnName = "column58";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 59},
							"configurator": function(cell){
								cell.columnName = "column59";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 60},
							"configurator": function(cell){
								cell.columnName = "column60";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 61},
							"configurator": function(cell){
								cell.columnName = "column61";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 62},
							"configurator": function(cell){
								cell.columnName = "column62";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 63},
							"configurator": function(cell){
								cell.columnName = "column63";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 64},
							"configurator": function(cell){
								cell.columnName = "column64";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 65},
							"configurator": function(cell){
								cell.columnName = "column65";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 66},
							"configurator": function(cell){
								cell.columnName = "column66";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 67},
							"configurator": function(cell){
								cell.columnName = "column67";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 68},
							"configurator": function(cell){
								cell.columnName = "column68";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 69},
							"configurator": function(cell){
								cell.columnName = "column69";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 70},
							"configurator": function(cell){
								cell.columnName = "column70";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 71},
							"configurator": function(cell){
								cell.columnName = "column71";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 72},
							"configurator": function(cell){
								cell.columnName = "column72";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 73},
							"configurator": function(cell){
								cell.columnName = "column73";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 74},
							"configurator": function(cell){
								cell.columnName = "column74";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 75},
							"configurator": function(cell){
								cell.columnName = "column75";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 76},
							"configurator": function(cell){
								cell.columnName = "column76";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 77},
							"configurator": function(cell){
								cell.columnName = "column77";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 78},
							"configurator": function(cell){
								cell.columnName = "column78";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 79},
							"configurator": function(cell){
								cell.columnName = "column79";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 80},
							"configurator": function(cell){
								cell.columnName = "column80";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 81},
							"configurator": function(cell){
								cell.columnName = "column81";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 82},
							"configurator": function(cell){
								cell.columnName = "column82";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 83},
							"configurator": function(cell){
								cell.columnName = "column83";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 84},
							"configurator": function(cell){
								cell.columnName = "column84";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 85},
							"configurator": function(cell){
								cell.columnName = "column85";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 86},
							"configurator": function(cell){
								cell.columnName = "column86";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 87},
							"configurator": function(cell){
								cell.columnName = "column87";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 88},
							"configurator": function(cell){
								cell.columnName = "column88";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 89},
							"configurator": function(cell){
								cell.columnName = "column89";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 90},
							"configurator": function(cell){
								cell.columnName = "column90";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 91},
							"configurator": function(cell){
								cell.columnName = "column91";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 92},
							"configurator": function(cell){
								cell.columnName = "column92";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 93},
							"configurator": function(cell){
								cell.columnName = "column93";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 94},
							"configurator": function(cell){
								cell.columnName = "column94";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 95},
							"configurator": function(cell){
								cell.columnName = "column95";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 96},
							"configurator": function(cell){
								cell.columnName = "column96";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 97},
							"configurator": function(cell){
								cell.columnName = "column97";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 98},
							"configurator": function(cell){
								cell.columnName = "column98";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 99},
							"configurator": function(cell){
								cell.columnName = "column99";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 100},
							"configurator": function(cell){
								cell.columnName = "column100";
							}
						}
					]
				}
			});
			if(typeof onGrd2Insert == "function") {
				grid_1.addEventListener("insert", onGrd2Insert);
			}
			container.addChild(grid_1, {
				"top": "50px",
				"right": "20px",
				"bottom": "20px",
				"left": "20px"
			});
			
			var button_1 = new cpr.controls.Button("btn3");
			button_1.value = "dsList에 데이터 적재";
			if(typeof onBtn3Click == "function") {
				button_1.addEventListener("click", onBtn3Click);
			}
			container.addChild(button_1, {
				"top": "20px",
				"left": "181px",
				"width": "167px",
				"height": "20px"
			});
			
			var button_2 = new cpr.controls.Button("btn4");
			button_2.value = "그리드의 데이터셋 dsList2 에서 dsList로 변경";
			if(typeof onBtn4Click == "function") {
				button_2.addEventListener("click", onBtn4Click);
			}
			container.addChild(button_2, {
				"top": "20px",
				"left": "358px",
				"width": "325px",
				"height": "20px"
			});
			
			var numberEditor_1 = new cpr.controls.NumberEditor("nbe1");
			container.addChild(numberEditor_1, {
				"top": "20px",
				"left": "20px",
				"width": "151px",
				"height": "20px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "helper";
	cpr.core.Platform.INSTANCE.register(app);
})();
