/*
 * App URI: 201909/ApStcs
 * Source Location: 201909/ApStcs.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("201909/ApStcs", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * ApStcs.js
			 * Created at 2019. 9. 26. 오후 4:34:52.
			 *
			 * @author HANS
			 ************************************************/
			
			
			
			/*
			 * 트리에서 selection-change 이벤트 발생 시 호출.
			 * 선택된 Item 값이 저장된 후에 발생하는 이벤트.
			 */
			function onTre1SelectionChange(/* cpr.events.CSelectionEvent */ e){
				/** 
				 * @type cpr.controls.Tree
				 */
				var tre1 = e.control;
				
				var as = app.lookup("appStack");
				
			}
			
			
			/*
			 * Body에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad(/* cpr.events.CEvent */ e){
				
				console.log("AppStcs화면에서 호출한 콘솔 ,hostAppInstance().id : " +app.getHostAppInstance().id);
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "label"},
					{"name": "value"},
					{"name": "parentValue"}
				],
				"rows": [
					{"label": "Deferred", "value": "201909/DeferredUpdateManager", "parentValue": ""},
					{"label": "dynamicGrid", "value": "201909/dynamicGrid", "parentValue": ""},
					{"label": "ep", "value": "201909/ep", "parentValue": ""},
					{"label": "right-icon", "value": "201909/right-icon", "parentValue": ""}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var userDefinedControl_1 = new udc.AppStack("appStack");
			container.addChild(userDefinedControl_1, {
				"top": "13px",
				"right": "20px",
				"bottom": "20px",
				"left": "258px"
			});
			
			var tree_1 = new cpr.controls.Tree("tre1");
			(function(tree_1){
				tree_1.setItemSet(app.lookup("ds1"), {
					"label": "label",
					"value": "value",
					"parentValue": "parentValue"
				});
			})(tree_1);
			if(typeof onTre1SelectionChange == "function") {
				tree_1.addEventListener("selection-change", onTre1SelectionChange);
			}
			container.addChild(tree_1, {
				"top": "13px",
				"bottom": "20px",
				"left": "7px",
				"width": "241px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "ApStcs";
	cpr.core.Platform.INSTANCE.register(app);
})();
