/*
 * App URI: 202104/comboListPop
 * Source Location: 202104/comboListPop.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("202104/comboListPop", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * ComboListPop.js
			 * Created at 2020. 5. 7. 오전 10:02:32.
			 *
			 * @author daye
			 ************************************************/
			
			var vbMobile = false;
			
			/*
			 * 사용자 정의 컨트롤에서 value-change 이벤트 발생 시 호출.
			 * 토글 버튼의 value를 변경하여 변경된 값이 저장되었을 때 발생하는 이벤트
			 */
			function onToggleButtonValueChange(/* cpr.events.CValueChangeEvent */ e){
				/** 
				 * @type udc.cmn.ToggleButton
				 */
				var toggleButton = e.control;
				
				vbMobile = !vbMobile;
				setComboPopMobile(vbMobile);
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("dsList");
			dataSet_1.parseData({
				"columns": [
					{"name": "label"},
					{"name": "value"}
				],
				"rows": [
					{"label": "label1", "value": "value1"},
					{"label": "label2", "value": "value2"},
					{"label": "label3", "value": "value3"},
					{"label": "label4", "value": "value4"},
					{"label": "label5", "value": "value5"},
					{"label": "label6", "value": "value6"},
					{"label": "label7", "value": "value7"}
				]
			});
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("dsPopList");
			dataSet_2.parseData({
				"columns": [
					{"name": "label"},
					{"name": "value"}
				],
				"rows": [
					{"label": "label1", "value": "value1"},
					{"label": "label2", "value": "value2"},
					{"label": "label3", "value": "value3"},
					{"label": "label4", "value": "value4"},
					{"label": "label5", "value": "value5"},
					{"label": "label6", "value": "value6"},
					{"label": "label7", "value": "value7"},
					{"label": "label8", "value": "value8"},
					{"label": "label9", "value": "value9"},
					{"label": "label10", "value": "value10"},
					{"label": "label11", "value": "value11"},
					{"label": "label12", "value": "value12"},
					{"label": "label13", "value": "value13"},
					{"label": "label14", "value": "value14"},
					{"label": "label15", "value": "value15"},
					{"label": "label16", "value": "value16"},
					{"label": "label17", "value": "value17"},
					{"label": "label18", "value": "value18"},
					{"label": "label19", "value": "value19"},
					{"label": "label20", "value": "value20"},
					{"label": "label21", "value": "value21"},
					{"label": "label22", "value": "value22"},
					{"label": "label23", "value": "value23"},
					{"label": "label24", "value": "value24"},
					{"label": "label25", "value": "value25"},
					{"label": "label26", "value": "value26"},
					{"label": "label27", "value": "value27"},
					{"label": "label28", "value": "value28"},
					{"label": "label29", "value": "value29"},
					{"label": "label30", "value": "value30"},
					{"label": "label31", "value": "value31"},
					{"label": "label32", "value": "value32"},
					{"label": "label33", "value": "value33"},
					{"label": "label34", "value": "value34"},
					{"label": "label35", "value": "value35"},
					{"label": "label36", "value": "value36"},
					{"label": "label37", "value": "value37"},
					{"label": "label38", "value": "value38"},
					{"label": "label39", "value": "value39"},
					{"label": "label40", "value": "value40"},
					{"label": "label41", "value": "value41"},
					{"label": "label42", "value": "value42"},
					{"label": "label43", "value": "value43"},
					{"label": "label44", "value": "value44"},
					{"label": "label45", "value": "value45"},
					{"label": "label46", "value": "value46"},
					{"label": "label47", "value": "value47"},
					{"label": "label48", "value": "value48"},
					{"label": "label49", "value": "value49"},
					{"label": "label50", "value": "value50"},
					{"label": "label51", "value": "value51"},
					{"label": "label52", "value": "value52"},
					{"label": "label53", "value": "value53"},
					{"label": "label54", "value": "value54"},
					{"label": "label55", "value": "value55"},
					{"label": "label56", "value": "value56"},
					{"label": "label57", "value": "value57"},
					{"label": "label58", "value": "value58"},
					{"label": "label59", "value": "value59"},
					{"label": "label60", "value": "value60"},
					{"label": "label61", "value": "value61"},
					{"label": "label62", "value": "value62"},
					{"label": "label63", "value": "value63"},
					{"label": "label64", "value": "value64"},
					{"label": "label65", "value": "value65"},
					{"label": "label66", "value": "value66"},
					{"label": "label67", "value": "value67"},
					{"label": "label68", "value": "value68"},
					{"label": "label69", "value": "value69"},
					{"label": "label70", "value": "value70"},
					{"label": "label71", "value": "value71"},
					{"label": "label72", "value": "value72"},
					{"label": "label73", "value": "value73"},
					{"label": "label74", "value": "value74"},
					{"label": "label75", "value": "value75"},
					{"label": "label76", "value": "value76"},
					{"label": "label77", "value": "value77"},
					{"label": "label78", "value": "value78"},
					{"label": "label79", "value": "value79"},
					{"label": "label80", "value": "value80"},
					{"label": "label81", "value": "value81"},
					{"label": "label82", "value": "value82"},
					{"label": "label83", "value": "value83"},
					{"label": "label84", "value": "value84"},
					{"label": "label85", "value": "value85"},
					{"label": "label86", "value": "value86"},
					{"label": "label87", "value": "value87"},
					{"label": "label88", "value": "value88"},
					{"label": "label89", "value": "value89"},
					{"label": "label90", "value": "value90"},
					{"label": "label91", "value": "value91"},
					{"label": "label92", "value": "value92"},
					{"label": "label93", "value": "value93"},
					{"label": "label94", "value": "value94"},
					{"label": "label95", "value": "value95"},
					{"label": "label96", "value": "value96"},
					{"label": "label97", "value": "value97"},
					{"label": "label98", "value": "value98"},
					{"label": "label99", "value": "value99"},
					{"label": "label100", "value": "value100"}
				]
			});
			app.register(dataSet_2);
			
			var dataSet_3 = new cpr.data.DataSet("dsGrid");
			dataSet_3.parseData({
				"columns": [
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"}
				],
				"rows": [{"column1": "column11", "column2": "column21", "column3": "column31"}]
			});
			app.register(dataSet_3);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var output_1 = new cpr.controls.Output();
			output_1.value = "프리폼";
			output_1.style.setClasses(["h6"]);
			container.addChild(output_1, {
				"top": "132px",
				"right": "10px",
				"left": "10px",
				"height": "28px"
			});
			
			var group_1 = new cpr.controls.Container();
			group_1.style.setClasses(["cl-form-group"]);
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.horizontalSeparatorWidth = 1;
			formLayout_1.verticalSeparatorWidth = 1;
			formLayout_1.setColumns(["200px", "1fr"]);
			formLayout_1.setUseColumnShade(0, true);
			formLayout_1.setColumnAutoSizing(0, true);
			formLayout_1.setRows(["30px", "30px", "30px", "30px"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var output_2 = new cpr.controls.Output();
				output_2.value = "기본 콤보박스 리스트 (cmb1)";
				container.addChild(output_2, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var output_3 = new cpr.controls.Output();
				output_3.value = "팝업(multiple=false) (cmb2)";
				container.addChild(output_3, {
					"colIndex": 0,
					"rowIndex": 1
				});
				var output_4 = new cpr.controls.Output();
				output_4.value = "팝업(multiple=true) (cmb3)";
				container.addChild(output_4, {
					"colIndex": 0,
					"rowIndex": 2
				});
				var comboBox_1 = new cpr.controls.ComboBox("cmb1");
				comboBox_1.fieldLabel = "기본 팝업 타이틀";
				comboBox_1.userAttr({"combo-pop": "true"});
				(function(comboBox_1){
					comboBox_1.setItemSet(app.lookup("dsList"), {
						"label": "label",
						"value": "value"
					});
				})(comboBox_1);
				container.addChild(comboBox_1, {
					"colIndex": 1,
					"rowIndex": 0,
					"horizontalAlign": "left",
					"width": 200
				});
				var comboBox_2 = new cpr.controls.ComboBox("cmb2");
				comboBox_2.fieldLabel = "단일선택 타이틀";
				comboBox_2.userAttr({"combo-pop": "true"});
				(function(comboBox_2){
					comboBox_2.setItemSet(app.lookup("dsPopList"), {
						"label": "label",
						"value": "value"
					});
				})(comboBox_2);
				container.addChild(comboBox_2, {
					"colIndex": 1,
					"rowIndex": 1,
					"horizontalAlign": "left",
					"width": 200
				});
				var comboBox_3 = new cpr.controls.ComboBox("cmb3");
				comboBox_3.fieldLabel = "다중선택 타이틀";
				comboBox_3.multiple = true;
				comboBox_3.userAttr({"combo-pop": "true"});
				(function(comboBox_3){
					comboBox_3.setItemSet(app.lookup("dsPopList"), {
						"label": "label",
						"value": "value"
					});
				})(comboBox_3);
				container.addChild(comboBox_3, {
					"colIndex": 1,
					"rowIndex": 2,
					"horizontalAlign": "left",
					"width": 200
				});
				var output_5 = new cpr.controls.Output();
				output_5.value = "target(기본콤보박스)";
				container.addChild(output_5, {
					"colIndex": 0,
					"rowIndex": 3
				});
				var button_1 = new cpr.controls.Button();
				button_1.fieldLabel = "cmb1";
				button_1.tooltip = "fieldLabel : cmb1";
				button_1.value = "click";
				button_1.style.setClasses(["btn-primary"]);
				container.addChild(button_1, {
					"colIndex": 1,
					"rowIndex": 3,
					"horizontalAlign": "left",
					"width": 80
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "170px",
				"right": "10px",
				"left": "10px",
				"height": "137px"
			});
			
			var output_6 = new cpr.controls.Output();
			output_6.value = "그리드 셀 (편집 행에서 콤보박스 및 버튼을 클릭해서 확인하십시오)";
			output_6.style.setClasses(["h6"]);
			container.addChild(output_6, {
				"top": "317px",
				"right": "10px",
				"left": "10px",
				"height": "28px"
			});
			
			var group_2 = new cpr.controls.Container();
			group_2.style.setClasses(["cl-form-group"]);
			// Layout
			var formLayout_2 = new cpr.controls.layouts.FormLayout();
			formLayout_2.topMargin = "1fr";
			formLayout_2.rightMargin = "5px";
			formLayout_2.bottomMargin = "1fr";
			formLayout_2.leftMargin = "5px";
			formLayout_2.horizontalSpacing = "10px";
			formLayout_2.verticalSpacing = "10px";
			formLayout_2.horizontalSeparatorWidth = 1;
			formLayout_2.verticalSeparatorWidth = 1;
			formLayout_2.setColumns(["120px", "1fr"]);
			formLayout_2.setUseColumnShade(0, true);
			formLayout_2.setColumnAutoSizing(0, true);
			formLayout_2.setRows(["24px"]);
			group_2.setLayout(formLayout_2);
			(function(container){
				var output_7 = new cpr.controls.Output();
				output_7.value = "모바일 버전";
				output_7.style.setClasses(["label"]);
				container.addChild(output_7, {
					"colIndex": 0,
					"rowIndex": 0
				});
			})(group_2);
			container.addChild(group_2, {
				"top": "20px",
				"right": "10px",
				"left": "10px",
				"height": "42px"
			});
			
			var output_8 = new cpr.controls.Output();
			output_8.value = "모바일 버전에서는 모든 콤보박스 아이템이 팝업을 통해 확인 할 수 있습니다.\r\n또한, 모니터에서 확인한 것과 다르게 아래에서 위로 뜨는 팝업형식으로 구성됩니다.";
			container.addChild(output_8, {
				"top": "72px",
				"right": "10px",
				"left": "10px",
				"height": "50px"
			});
		}
	});
	app.title = "콤보박스 리스트 팝업";
	cpr.core.Platform.INSTANCE.register(app);
})();
