/*
 * App URI: 202104/flowTest
 * Source Location: 202104/flowTest.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("202104/flowTest", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * flowTest.js
			 * Created at 2021. 4. 15. 오후 2:08:56.
			 *
			 * @author HANS
			 ************************************************/
			var index = 5;
			
			
			
			var btns;
			/*
			 * 루트 컨테이너에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad(/* cpr.events.CEvent */ e){
				
			//	btns = new cpr.controls.Container();
			//	
			//	var flows = new cpr.controls.layouts.FlowLayout();
			//	
			//	flows.horizontalAlign = "center";
			//	flows.verticalAlign = "middle";
			//	flows.lineWrap = false;
			//	flows.scrollable = false;
			//	flows.spacing = 12;
			//	flows.topMargin = 36;
			//	flows.rightMargin = 0;
			//	flows.bottomMargin = 48;
			//	flows.leftMargin = 0;
			//	
			//	btns.setLayout(flows);
			//	
			//	
			////	for(var i = 0 ; i < 0 ; i++) {
			//		
			//		var btt = new cpr.controls.Button();
			//		btt.value = "Zzz";
			//		
			//		btns.addChild(btt, {
			//				width: "6px",
			//				height: "6px",
			//				autoSize: "both"
			//		});
			////	}
			//	
			//	app.lookup("grp1").floatControl(btns);
			
			}
			
			
			/*
			 * "true" 버튼(btn1)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn1 = e.control;
				app.lookup("grpForm").visible = true;
			}
			
			
			/*
			 * "false" 버튼(btn2)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn2Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn2 = e.control;
				
				app.lookup("grpForm").visible = false;
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
			container.setLayout(flowLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grp1");
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			group_1.setLayout(verticalLayout_1);
			(function(container){
				var button_1 = new cpr.controls.Button("btn1");
				button_1.value = "true";
				if(typeof onBtn1Click == "function") {
					button_1.addEventListener("click", onBtn1Click);
				}
				container.addChild(button_1, {
					"width": "100px",
					"height": "20px"
				});
				var button_2 = new cpr.controls.Button("btn2");
				button_2.value = "false";
				if(typeof onBtn2Click == "function") {
					button_2.addEventListener("click", onBtn2Click);
				}
				container.addChild(button_2, {
					"width": "100px",
					"height": "20px"
				});
				var group_2 = new cpr.controls.Container("grpForm");
				group_2.visible = false;
				group_2.userAttr({"swipe-depth": ""});
				group_2.style.setClasses(["card"]);
				// Layout
				var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_2.spacing = 10;
				verticalLayout_2.leftMargin = 15;
				verticalLayout_2.rightMargin = 15;
				verticalLayout_2.topMargin = 20;
				verticalLayout_2.bottomMargin = 20;
				group_2.setLayout(verticalLayout_2);
				(function(container){
					var output_1 = new cpr.controls.Output();
					output_1.value = "재산/부채 사항";
					output_1.style.setClasses(["h4"]);
					container.addChild(output_1, {
						"autoSize": "height",
						"width": "100px",
						"height": "20px"
					});
					var group_3 = new cpr.controls.Container("grp2");
					group_3.style.setClasses(["form-table"]);
					// Layout
					var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_3.spacing = 0;
					group_3.setLayout(verticalLayout_3);
					(function(container){
						var group_4 = new cpr.controls.Container("grp3");
						group_4.style.setClasses(["form-info-field"]);
						// Layout
						var formLayout_1 = new cpr.controls.layouts.FormLayout();
						formLayout_1.topMargin = "20px";
						formLayout_1.rightMargin = "0px";
						formLayout_1.bottomMargin = "20px";
						formLayout_1.leftMargin = "10px";
						formLayout_1.horizontalSpacing = "0px";
						formLayout_1.verticalSpacing = "16px";
						formLayout_1.setColumns(["140px", "1fr"]);
						formLayout_1.setRows(["20px"]);
						group_4.setLayout(formLayout_1);
						(function(container){
							var output_2 = new cpr.controls.Output();
							output_2.value = "성명";
							output_2.style.setClasses(["info-label"]);
							container.addChild(output_2, {
								"colIndex": 0,
								"rowIndex": 0
							});
							var output_3 = new cpr.controls.Output();
							output_3.value = "홍길동";
							output_3.style.setClasses(["info-val"]);
							container.addChild(output_3, {
								"colIndex": 1,
								"rowIndex": 0
							});
						})(group_4);
						container.addChild(group_4, {
							"autoSize": "height",
							"width": "345px",
							"height": "60px"
						});
						var group_5 = new cpr.controls.Container("grp4");
						group_5.style.setClasses(["table"]);
						// Layout
						var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_4.spacing = 0;
						group_5.setLayout(verticalLayout_4);
						(function(container){
							var group_6 = new cpr.controls.Container("grp5");
							// Layout
							var verticalLayout_5 = new cpr.controls.layouts.VerticalLayout();
							verticalLayout_5.spacing = 0;
							group_6.setLayout(verticalLayout_5);
							(function(container){
								var group_7 = new cpr.controls.Container("grp6");
								group_7.style.setClasses(["table-header"]);
								// Layout
								var formLayout_2 = new cpr.controls.layouts.FormLayout();
								formLayout_2.topMargin = "0px";
								formLayout_2.rightMargin = "0px";
								formLayout_2.bottomMargin = "0px";
								formLayout_2.leftMargin = "0px";
								formLayout_2.horizontalSpacing = "0px";
								formLayout_2.verticalSpacing = "0px";
								formLayout_2.setColumns(["1fr"]);
								formLayout_2.setRows(["1fr"]);
								formLayout_2.setUseRowShade(0, true);
								group_7.setLayout(formLayout_2);
								(function(container){
									var output_4 = new cpr.controls.Output();
									output_4.value = "재산 사항 (임차보증금)";
									output_4.style.setClasses(["table-cell"]);
									container.addChild(output_4, {
										"colIndex": 0,
										"rowIndex": 0
									});
								})(group_7);
								container.addChild(group_7, {
									"width": "345px",
									"height": "60px"
								});
								var group_8 = new cpr.controls.Container("grp7");
								group_8.style.setClasses(["table-detail"]);
								// Layout
								var verticalLayout_6 = new cpr.controls.layouts.VerticalLayout();
								verticalLayout_6.spacing = 0;
								group_8.setLayout(verticalLayout_6);
								(function(container){
									var group_9 = new cpr.controls.Container("grp8");
									group_9.style.setClasses(["table-row", "dashed", "table-cell"]);
									// Layout
									var formLayout_3 = new cpr.controls.layouts.FormLayout();
									formLayout_3.topMargin = "6px";
									formLayout_3.rightMargin = "0px";
									formLayout_3.bottomMargin = "6px";
									formLayout_3.leftMargin = "0px";
									formLayout_3.horizontalSpacing = "6px";
									formLayout_3.verticalSpacing = "6px";
									formLayout_3.setColumns(["1fr", "155px"]);
									formLayout_3.setRows(["48px"]);
									group_9.setLayout(formLayout_3);
									(function(container){
										var output_5 = new cpr.controls.Output();
										output_5.value = "전·월세 보증금";
										output_5.style.setClasses(["label"]);
										container.addChild(output_5, {
											"colIndex": 0,
											"rowIndex": 0
										});
										var group_10 = new cpr.controls.Container("grp9");
										// Layout
										var formLayout_4 = new cpr.controls.layouts.FormLayout();
										formLayout_4.topMargin = "0px";
										formLayout_4.rightMargin = "0px";
										formLayout_4.bottomMargin = "0px";
										formLayout_4.leftMargin = "0px";
										formLayout_4.horizontalSpacing = "10px";
										formLayout_4.verticalSpacing = "10px";
										formLayout_4.setColumns(["1fr", "10px"]);
										formLayout_4.setColumnAutoSizing(1, true);
										formLayout_4.setRows(["1fr"]);
										group_10.setLayout(formLayout_4);
										(function(container){
											var numberEditor_1 = new cpr.controls.NumberEditor("nbe3");
											numberEditor_1.spinButton = false;
											container.addChild(numberEditor_1, {
												"colIndex": 0,
												"rowIndex": 0
											});
											var output_6 = new cpr.controls.Output();
											output_6.value = "원";
											container.addChild(output_6, {
												"colIndex": 1,
												"rowIndex": 0
											});
										})(group_10);
										container.addChild(group_10, {
											"colIndex": 1,
											"rowIndex": 0
										});
									})(group_9);
									container.addChild(group_9, {
										"width": "400px",
										"height": "60px"
									});
									var group_11 = new cpr.controls.Container("grp10");
									group_11.style.setClasses(["table-row", "dashed", "table-cell"]);
									// Layout
									var formLayout_5 = new cpr.controls.layouts.FormLayout();
									formLayout_5.topMargin = "6px";
									formLayout_5.rightMargin = "0px";
									formLayout_5.bottomMargin = "6px";
									formLayout_5.leftMargin = "0px";
									formLayout_5.horizontalSpacing = "6px";
									formLayout_5.verticalSpacing = "6px";
									formLayout_5.setColumns(["1fr", "155px"]);
									formLayout_5.setRows(["48px"]);
									group_11.setLayout(formLayout_5);
									(function(container){
										var output_7 = new cpr.controls.Output();
										output_7.value = "상가보증금";
										output_7.style.setClasses(["label"]);
										container.addChild(output_7, {
											"colIndex": 0,
											"rowIndex": 0
										});
										var group_12 = new cpr.controls.Container("grp11");
										// Layout
										var formLayout_6 = new cpr.controls.layouts.FormLayout();
										formLayout_6.topMargin = "0px";
										formLayout_6.rightMargin = "0px";
										formLayout_6.bottomMargin = "0px";
										formLayout_6.leftMargin = "0px";
										formLayout_6.horizontalSpacing = "10px";
										formLayout_6.verticalSpacing = "10px";
										formLayout_6.setColumns(["1fr", "10px"]);
										formLayout_6.setColumnAutoSizing(1, true);
										formLayout_6.setRows(["1fr"]);
										group_12.setLayout(formLayout_6);
										(function(container){
											var numberEditor_2 = new cpr.controls.NumberEditor("nbe4");
											numberEditor_2.spinButton = false;
											container.addChild(numberEditor_2, {
												"colIndex": 0,
												"rowIndex": 0
											});
											var output_8 = new cpr.controls.Output();
											output_8.value = "원";
											container.addChild(output_8, {
												"colIndex": 1,
												"rowIndex": 0
											});
										})(group_12);
										container.addChild(group_12, {
											"colIndex": 1,
											"rowIndex": 0
										});
									})(group_11);
									container.addChild(group_11, {
										"width": "400px",
										"height": "60px"
									});
									var group_13 = new cpr.controls.Container("grp12");
									group_13.style.setClasses(["table-row", "dashed", "table-cell"]);
									// Layout
									var formLayout_7 = new cpr.controls.layouts.FormLayout();
									formLayout_7.topMargin = "6px";
									formLayout_7.rightMargin = "0px";
									formLayout_7.bottomMargin = "6px";
									formLayout_7.leftMargin = "0px";
									formLayout_7.horizontalSpacing = "6px";
									formLayout_7.verticalSpacing = "6px";
									formLayout_7.setColumns(["1fr", "155px"]);
									formLayout_7.setRows(["48px"]);
									group_13.setLayout(formLayout_7);
									(function(container){
										var output_9 = new cpr.controls.Output();
										output_9.value = "주택, 상가 외 기타 보증금";
										output_9.style.setClasses(["label"]);
										container.addChild(output_9, {
											"colIndex": 0,
											"rowIndex": 0
										});
										var group_14 = new cpr.controls.Container("grp13");
										// Layout
										var formLayout_8 = new cpr.controls.layouts.FormLayout();
										formLayout_8.topMargin = "0px";
										formLayout_8.rightMargin = "0px";
										formLayout_8.bottomMargin = "0px";
										formLayout_8.leftMargin = "0px";
										formLayout_8.horizontalSpacing = "10px";
										formLayout_8.verticalSpacing = "10px";
										formLayout_8.setColumns(["1fr", "10px"]);
										formLayout_8.setColumnAutoSizing(1, true);
										formLayout_8.setRows(["1fr"]);
										group_14.setLayout(formLayout_8);
										(function(container){
											var numberEditor_3 = new cpr.controls.NumberEditor("nbe5");
											numberEditor_3.spinButton = false;
											container.addChild(numberEditor_3, {
												"colIndex": 0,
												"rowIndex": 0
											});
											var output_10 = new cpr.controls.Output();
											output_10.value = "원";
											container.addChild(output_10, {
												"colIndex": 1,
												"rowIndex": 0
											});
										})(group_14);
										container.addChild(group_14, {
											"colIndex": 1,
											"rowIndex": 0
										});
									})(group_13);
									container.addChild(group_13, {
										"width": "400px",
										"height": "60px"
									});
								})(group_8);
								container.addChild(group_8, {
									"autoSize": "height",
									"width": "345px",
									"height": "180px"
								});
							})(group_6);
							container.addChild(group_6, {
								"autoSize": "height",
								"width": "400px",
								"height": "248px"
							});
							var group_15 = new cpr.controls.Container("grp14");
							// Layout
							var verticalLayout_7 = new cpr.controls.layouts.VerticalLayout();
							verticalLayout_7.spacing = 0;
							group_15.setLayout(verticalLayout_7);
							(function(container){
								var group_16 = new cpr.controls.Container("grp15");
								group_16.style.setClasses(["table-header"]);
								// Layout
								var formLayout_9 = new cpr.controls.layouts.FormLayout();
								formLayout_9.topMargin = "0px";
								formLayout_9.rightMargin = "0px";
								formLayout_9.bottomMargin = "0px";
								formLayout_9.leftMargin = "0px";
								formLayout_9.horizontalSpacing = "0px";
								formLayout_9.verticalSpacing = "0px";
								formLayout_9.setColumns(["1fr"]);
								formLayout_9.setRows(["1fr"]);
								formLayout_9.setUseRowShade(0, true);
								group_16.setLayout(formLayout_9);
								(function(container){
									var output_11 = new cpr.controls.Output();
									output_11.value = "부채 사항 (대출금 및 임대보증금)";
									output_11.style.setClasses(["table-cell"]);
									container.addChild(output_11, {
										"colIndex": 0,
										"rowIndex": 0
									});
								})(group_16);
								container.addChild(group_16, {
									"width": "345px",
									"height": "60px"
								});
								var group_17 = new cpr.controls.Container("grp16");
								group_17.style.setClasses(["table-detail"]);
								// Layout
								var verticalLayout_8 = new cpr.controls.layouts.VerticalLayout();
								verticalLayout_8.spacing = 0;
								group_17.setLayout(verticalLayout_8);
								(function(container){
									var group_18 = new cpr.controls.Container("grp17");
									group_18.style.setClasses(["table-row", "dashed", "table-cell"]);
									// Layout
									var formLayout_10 = new cpr.controls.layouts.FormLayout();
									formLayout_10.topMargin = "6px";
									formLayout_10.rightMargin = "0px";
									formLayout_10.bottomMargin = "6px";
									formLayout_10.leftMargin = "0px";
									formLayout_10.horizontalSpacing = "6px";
									formLayout_10.verticalSpacing = "6px";
									formLayout_10.setColumns(["1fr", "155px"]);
									formLayout_10.setRows(["48px"]);
									group_18.setLayout(formLayout_10);
									(function(container){
										var output_12 = new cpr.controls.Output();
										output_12.value = "전·월세 보증금";
										output_12.style.setClasses(["label"]);
										container.addChild(output_12, {
											"colIndex": 0,
											"rowIndex": 0
										});
										var group_19 = new cpr.controls.Container("grp18");
										// Layout
										var formLayout_11 = new cpr.controls.layouts.FormLayout();
										formLayout_11.topMargin = "0px";
										formLayout_11.rightMargin = "0px";
										formLayout_11.bottomMargin = "0px";
										formLayout_11.leftMargin = "0px";
										formLayout_11.horizontalSpacing = "10px";
										formLayout_11.verticalSpacing = "10px";
										formLayout_11.setColumns(["1fr", "10px"]);
										formLayout_11.setColumnAutoSizing(1, true);
										formLayout_11.setRows(["1fr"]);
										group_19.setLayout(formLayout_11);
										(function(container){
											var numberEditor_4 = new cpr.controls.NumberEditor("nbe6");
											numberEditor_4.spinButton = false;
											container.addChild(numberEditor_4, {
												"colIndex": 0,
												"rowIndex": 0
											});
											var output_13 = new cpr.controls.Output();
											output_13.value = "원";
											container.addChild(output_13, {
												"colIndex": 1,
												"rowIndex": 0
											});
										})(group_19);
										container.addChild(group_19, {
											"colIndex": 1,
											"rowIndex": 0
										});
									})(group_18);
									container.addChild(group_18, {
										"width": "400px",
										"height": "60px"
									});
									var group_20 = new cpr.controls.Container("grp19");
									group_20.style.setClasses(["table-row", "dashed", "table-cell"]);
									// Layout
									var formLayout_12 = new cpr.controls.layouts.FormLayout();
									formLayout_12.topMargin = "6px";
									formLayout_12.rightMargin = "0px";
									formLayout_12.bottomMargin = "6px";
									formLayout_12.leftMargin = "0px";
									formLayout_12.horizontalSpacing = "6px";
									formLayout_12.verticalSpacing = "6px";
									formLayout_12.setColumns(["1fr", "155px"]);
									formLayout_12.setRows(["48px"]);
									group_20.setLayout(formLayout_12);
									(function(container){
										var output_14 = new cpr.controls.Output();
										output_14.value = "상가보증금";
										output_14.style.setClasses(["label"]);
										container.addChild(output_14, {
											"colIndex": 0,
											"rowIndex": 0
										});
										var group_21 = new cpr.controls.Container("grp20");
										// Layout
										var formLayout_13 = new cpr.controls.layouts.FormLayout();
										formLayout_13.topMargin = "0px";
										formLayout_13.rightMargin = "0px";
										formLayout_13.bottomMargin = "0px";
										formLayout_13.leftMargin = "0px";
										formLayout_13.horizontalSpacing = "10px";
										formLayout_13.verticalSpacing = "10px";
										formLayout_13.setColumns(["1fr", "10px"]);
										formLayout_13.setColumnAutoSizing(1, true);
										formLayout_13.setRows(["1fr"]);
										group_21.setLayout(formLayout_13);
										(function(container){
											var numberEditor_5 = new cpr.controls.NumberEditor("nbe7");
											numberEditor_5.spinButton = false;
											container.addChild(numberEditor_5, {
												"colIndex": 0,
												"rowIndex": 0
											});
											var output_15 = new cpr.controls.Output();
											output_15.value = "원";
											container.addChild(output_15, {
												"colIndex": 1,
												"rowIndex": 0
											});
										})(group_21);
										container.addChild(group_21, {
											"colIndex": 1,
											"rowIndex": 0
										});
									})(group_20);
									container.addChild(group_20, {
										"width": "400px",
										"height": "60px"
									});
									var group_22 = new cpr.controls.Container("grp21");
									group_22.style.setClasses(["table-row", "dashed", "table-cell"]);
									// Layout
									var formLayout_14 = new cpr.controls.layouts.FormLayout();
									formLayout_14.topMargin = "6px";
									formLayout_14.rightMargin = "0px";
									formLayout_14.bottomMargin = "6px";
									formLayout_14.leftMargin = "0px";
									formLayout_14.horizontalSpacing = "6px";
									formLayout_14.verticalSpacing = "6px";
									formLayout_14.setColumns(["1fr", "155px"]);
									formLayout_14.setRows(["48px"]);
									group_22.setLayout(formLayout_14);
									(function(container){
										var output_16 = new cpr.controls.Output();
										output_16.value = "주택, 상가 외 기타 보증금";
										output_16.style.setClasses(["label"]);
										container.addChild(output_16, {
											"colIndex": 0,
											"rowIndex": 0
										});
										var group_23 = new cpr.controls.Container("grp22");
										// Layout
										var formLayout_15 = new cpr.controls.layouts.FormLayout();
										formLayout_15.topMargin = "0px";
										formLayout_15.rightMargin = "0px";
										formLayout_15.bottomMargin = "0px";
										formLayout_15.leftMargin = "0px";
										formLayout_15.horizontalSpacing = "10px";
										formLayout_15.verticalSpacing = "10px";
										formLayout_15.setColumns(["1fr", "10px"]);
										formLayout_15.setColumnAutoSizing(1, true);
										formLayout_15.setRows(["1fr"]);
										group_23.setLayout(formLayout_15);
										(function(container){
											var numberEditor_6 = new cpr.controls.NumberEditor("nbe8");
											numberEditor_6.spinButton = false;
											container.addChild(numberEditor_6, {
												"colIndex": 0,
												"rowIndex": 0
											});
											var output_17 = new cpr.controls.Output();
											output_17.value = "원";
											container.addChild(output_17, {
												"colIndex": 1,
												"rowIndex": 0
											});
										})(group_23);
										container.addChild(group_23, {
											"colIndex": 1,
											"rowIndex": 0
										});
									})(group_22);
									container.addChild(group_22, {
										"width": "400px",
										"height": "60px"
									});
								})(group_17);
								container.addChild(group_17, {
									"autoSize": "height",
									"width": "345px",
									"height": "180px"
								});
							})(group_15);
							container.addChild(group_15, {
								"autoSize": "height",
								"width": "345px",
								"height": "248px"
							});
						})(group_5);
						container.addChild(group_5, {
							"autoSize": "height",
							"width": "400px",
							"height": "551px"
						});
					})(group_3);
					container.addChild(group_3, {
						"autoSize": "height",
						"width": "1134px",
						"height": "652px"
					});
				})(group_2);
				container.addChild(group_2, {
					"autoSize": "height",
					"width": "375px",
					"height": "692px"
				});
			})(group_1);
			if(typeof onGrp1MeasureSize == "function") {
				group_1.addEventListener("measure-size", onGrp1MeasureSize);
			}
			if(typeof onGrp1BeforeDraw == "function") {
				group_1.addEventListener("before-draw", onGrp1BeforeDraw);
			}
			if(typeof onGrp1Scroll == "function") {
				group_1.addEventListener("scroll", onGrp1Scroll);
			}
			container.addChild(group_1, {
				"autoSize": "height",
				"width": "100%",
				"height": "417px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "flowTest";
	cpr.core.Platform.INSTANCE.register(app);
})();
