/*
 * App URI: 202110/mdiTester
 * Source Location: 202110/mdiTester.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("202110/mdiTester", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * mdiTester.js
			 * Created at 2021. 10. 15. 오후 1:20:10.
			 *
			 * @author HANS
			 ************************************************/
			
			
			
			
			/*
			 * MDI 폴더에서 selection-change 이벤트 발생 시 호출.
			 * Tab Item을 선택한 후에 발생하는 이벤트.
			 */
			function onMdi1SelectionChange(/* cpr.events.CSelectionEvent */ e){
				/** 
				 * @type cpr.controls.MDIFolder
				 */
				var mdi1 = e.control;
				console.log(e.newSelection.text);
				cpr.core.NotificationCenter.INSTANCE.post("SELECTIONCHANGERMAN", {
					type : "MANDU",
					inner : "KIMCHI"
				},e.newSelection.text);
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var mDIFolder_1 = new cpr.controls.MDIFolder("mdi1");
			
			var tabItem_1 = (function(tabFolder){
				var tabItem_1 = new cpr.controls.TabItem();
				tabItem_1.text = "one";
				var embeddedApp_1 = new cpr.controls.EmbeddedApp("ea1");
				cpr.core.App.load("202110/scrollTo", function(app) {
					if(app){
						embeddedApp_1.app = app;
					}
				});
				tabItem_1.content = embeddedApp_1;
				return tabItem_1;
			})(mDIFolder_1);
			mDIFolder_1.addTabItem(tabItem_1);
			
			var tabItem_2 = (function(tabFolder){
				var tabItem_2 = new cpr.controls.TabItem();
				tabItem_2.text = "two";
				var embeddedApp_2 = new cpr.controls.EmbeddedApp("ea2");
				cpr.core.App.load("202110/tester", function(app) {
					if(app){
						embeddedApp_2.app = app;
					}
				});
				tabItem_2.content = embeddedApp_2;
				return tabItem_2;
			})(mDIFolder_1);
			mDIFolder_1.addTabItem(tabItem_2);
			
			var tabItem_3 = (function(tabFolder){
				var tabItem_3 = new cpr.controls.TabItem();
				tabItem_3.text = "poper.clx";
				var embeddedApp_3 = new cpr.controls.EmbeddedApp("ea3");
				cpr.core.App.load("202110/poper", function(app) {
					if(app){
						embeddedApp_3.app = app;
					}
				});
				tabItem_3.content = embeddedApp_3;
				return tabItem_3;
			})(mDIFolder_1);
			mDIFolder_1.addTabItem(tabItem_3);
			mDIFolder_1.setSelectedTabItem(tabItem_2);
			if(typeof onMdi1SelectionChange == "function") {
				mDIFolder_1.addEventListener("selection-change", onMdi1SelectionChange);
			}
			container.addChild(mDIFolder_1, {
				"top": "37px",
				"left": "20px",
				"width": "862px",
				"height": "433px"
			});
		}
	});
	app.title = "mdiTester";
	cpr.core.Platform.INSTANCE.register(app);
})();
