/*
 * App URI: 202102/Dashboard
 * Source Location: 202102/Dashboard.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("202102/Dashboard", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * Dashboard.js
			 * Created at 2021. 2. 17. 오후 4:18:56.
			 *
			 * @author ryu
			 ************************************************/;
			// End - User Script
			
			// Header
			
			app.supportMedia("all", "default");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.distribution = "center";
			verticalLayout_1.spacing = 0;
			verticalLayout_1.leftMargin = 0;
			verticalLayout_1.rightMargin = 0;
			verticalLayout_1.topMargin = 70;
			verticalLayout_1.bottomMargin = 80;
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			group_1.clipContent = false;
			group_1.style.setClasses(["keyword-cont"]);
			// Layout
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_2.scrollable = false;
			verticalLayout_2.distribution = "center";
			verticalLayout_2.spacing = 18;
			verticalLayout_2.bottomMargin = 56;
			group_1.setLayout(verticalLayout_2);
			(function(container){
				var group_2 = new cpr.controls.Container();
				group_2.clipContent = false;
				// Layout
				var xYLayout_1 = new cpr.controls.layouts.XYLayout();
				xYLayout_1.scrollable = false;
				group_2.setLayout(xYLayout_1);
				(function(container){
					var inputBox_1 = new cpr.controls.InputBox("ipb1");
					inputBox_1.placeholder = "검색어를 입력하세요";
					inputBox_1.style.setClasses(["keyword-search"]);
					container.addChild(inputBox_1, {
						"top": "0px",
						"right": "0px",
						"bottom": "0px",
						"left": "0px"
					});
					var button_1 = new cpr.controls.Button();
					button_1.value = "";
					button_1.icon = "../theme/images/com/main/das/ico_btn_search_w.png";
					button_1.style.setClasses(["btn-keyword-search"]);
					container.addChild(button_1, {
						"top": "0px",
						"right": "0px",
						"bottom": "0px",
						"width": "72px"
					});
				})(group_2);
				container.addChild(group_2, {
					"width": "592px",
					"height": "72px"
				});
				var group_3 = new cpr.controls.Container();
				group_3.clipContent = false;
				group_3.style.setClasses(["keyword-tags"]);
				// Layout
				var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
				flowLayout_1.scrollable = false;
				flowLayout_1.horizontalSpacing = 23;
				flowLayout_1.verticalSpacing = 23;
				flowLayout_1.lineWrap = false;
				group_3.setLayout(flowLayout_1);
				(function(container){
					var output_1 = new cpr.controls.Output();
					output_1.value = "# 출산지원";
					container.addChild(output_1, {
						"autoSize": "width",
						"width": "100px",
						"height": "16px"
					});
					var output_2 = new cpr.controls.Output();
					output_2.value = "# 차상위계층";
					container.addChild(output_2, {
						"autoSize": "width",
						"width": "100px",
						"height": "16px"
					});
					var output_3 = new cpr.controls.Output();
					output_3.value = "# 난임부부시술비지원";
					container.addChild(output_3, {
						"autoSize": "width",
						"width": "100px",
						"height": "16px"
					});
					var output_4 = new cpr.controls.Output();
					output_4.value = "# 통합문화이용권";
					container.addChild(output_4, {
						"autoSize": "width",
						"width": "100px",
						"height": "16px"
					});
				})(group_3);
				container.addChild(group_3, {
					"autoSize": "width",
					"width": "592px",
					"height": "16px"
				});
			})(group_1);
			container.addChild(group_1, {
				"autoSize": "both",
				"width": "592px",
				"height": "162px"
			});
			
			var group_4 = new cpr.controls.Container();
			// Layout
			var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_3.topMargin = 0;
			verticalLayout_3.bottomMargin = 70;
			group_4.setLayout(verticalLayout_3);
			(function(container){
				var group_5 = new cpr.controls.Container();
				group_5.style.setClasses(["frequent-service-cont"]);
				// Layout
				var formLayout_1 = new cpr.controls.layouts.FormLayout();
				formLayout_1.topMargin = "0px";
				formLayout_1.rightMargin = "0px";
				formLayout_1.bottomMargin = "0px";
				formLayout_1.leftMargin = "43px";
				formLayout_1.horizontalSpacing = "0px";
				formLayout_1.verticalSpacing = "0px";
				formLayout_1.setColumns(["100px", "1fr"]);
				formLayout_1.setRows(["1fr"]);
				group_5.setLayout(formLayout_1);
				(function(container){
					var group_6 = new cpr.controls.Container();
					group_6.style.setClasses(["frequent-service-txt"]);
					// Layout
					var verticalLayout_4 = new cpr.controls.layouts.VerticalLayout();
					verticalLayout_4.spacing = 57;
					verticalLayout_4.topMargin = 55;
					group_6.setLayout(verticalLayout_4);
					(function(container){
						var output_5 = new cpr.controls.Output();
						output_5.value = "자주 찾는 서비스";
						output_5.style.setClasses(["tit"]);
						container.addChild(output_5, {
							"autoSize": "height",
							"width": "100px",
							"height": "50px"
						});
						var button_2 = new cpr.controls.Button();
						button_2.value = "메뉴설정";
						button_2.icon = "../theme/images/com/main/das/ico_setting.png";
						button_2.style.setClasses(["btn-frequent-service", "btn-transparent"]);
						container.addChild(button_2, {
							"autoSize": "width",
							"width": "100px",
							"height": "20px"
						});
					})(group_6);
					container.addChild(group_6, {
						"colIndex": 0,
						"rowIndex": 0
					});
					var group_7 = new cpr.controls.Container();
					group_7.style.setClasses(["frequent-service-slide"]);
					// Layout
					var flowLayout_2 = new cpr.controls.layouts.FlowLayout();
					flowLayout_2.horizontalSpacing = 62;
					flowLayout_2.verticalSpacing = 62;
					flowLayout_2.verticalAlign = "middle";
					flowLayout_2.lineWrap = false;
					flowLayout_2.leftMargin = 77;
					flowLayout_2.rightMargin = 72;
					flowLayout_2.topMargin = 48;
					flowLayout_2.bottomMargin = 0;
					group_7.setLayout(flowLayout_2);
					(function(container){
						var button_3 = new cpr.controls.Button();
						button_3.value = "복지지갑";
						button_3.icon = "../theme/images/com/main/das/ico_menu_01.png";
						button_3.iconAlign = "top";
						button_3.style.setClasses(["service-item"]);
						container.addChild(button_3, {
							"width": "104px",
							"height": "136px"
						});
						var button_4 = new cpr.controls.Button();
						button_4.value = "모의계산";
						button_4.icon = "../theme/images/com/main/das/ico_menu_02.png";
						button_4.iconAlign = "top";
						button_4.style.setClasses(["service-item"]);
						container.addChild(button_4, {
							"width": "104px",
							"height": "136px"
						});
						var button_5 = new cpr.controls.Button();
						button_5.value = "서비스신청";
						button_5.icon = "../theme/images/com/main/das/ico_menu_03.png";
						button_5.iconAlign = "top";
						button_5.style.setClasses(["service-item"]);
						container.addChild(button_5, {
							"width": "104px",
							"height": "136px"
						});
						var button_6 = new cpr.controls.Button();
						button_6.value = "증명서발급";
						button_6.icon = "../theme/images/com/main/das/ico_menu_04.png";
						button_6.iconAlign = "top";
						button_6.style.setClasses(["service-item"]);
						container.addChild(button_6, {
							"width": "104px",
							"height": "136px"
						});
						var button_7 = new cpr.controls.Button();
						button_7.value = "복지서비스";
						button_7.icon = "../theme/images/com/main/das/ico_menu_05.png";
						button_7.iconAlign = "top";
						button_7.style.setClasses(["service-item"]);
						container.addChild(button_7, {
							"width": "104px",
							"height": "136px"
						});
						var button_8 = new cpr.controls.Button();
						button_8.value = "부정수급신고";
						button_8.icon = "../theme/images/com/main/das/ico_menu_06.png";
						button_8.iconAlign = "top";
						button_8.style.setClasses(["service-item"]);
						container.addChild(button_8, {
							"width": "104px",
							"height": "136px"
						});
						var button_9 = new cpr.controls.Button();
						button_9.value = "급여계좌변경";
						button_9.icon = "../theme/images/com/main/das/ico_menu_07.png";
						button_9.iconAlign = "top";
						button_9.style.setClasses(["service-item"]);
						container.addChild(button_9, {
							"autoSize": "none",
							"width": "104px",
							"height": "136px"
						});
						var button_10 = new cpr.controls.Button();
						button_10.value = "자격증명관리";
						button_10.icon = "../theme/images/com/main/das/ico_menu_08.png";
						button_10.iconAlign = "top";
						button_10.style.setClasses(["service-item"]);
						container.addChild(button_10, {
							"autoSize": "none",
							"width": "104px",
							"height": "136px"
						});
						var button_11 = new cpr.controls.Button();
						button_11.value = "복지시설";
						button_11.icon = "../theme/images/com/main/das/ico_menu_09.png";
						button_11.iconAlign = "top";
						button_11.style.setClasses(["service-item"]);
						container.addChild(button_11, {
							"autoSize": "none",
							"width": "104px",
							"height": "136px"
						});
						var button_12 = new cpr.controls.Button();
						button_12.value = "신청서식";
						button_12.icon = "../theme/images/com/main/das/ico_menu_10.png";
						button_12.iconAlign = "top";
						button_12.style.setClasses(["service-item"]);
						container.addChild(button_12, {
							"autoSize": "none",
							"width": "104px",
							"height": "136px"
						});
					})(group_7);
					container.addChild(group_7, {
						"colIndex": 1,
						"rowIndex": 0
					});
				})(group_5);
				container.addChild(group_5, {
					"width": "400px",
					"height": "232px"
				});
			})(group_4);
			container.addChild(group_4, {
				"autoSize": "none",
				"width": "1216px",
				"height": "302px"
			});
			
			var group_8 = new cpr.controls.Container();
			group_8.style.setClasses(["welfare-service-cont"]);
			// Layout
			var verticalLayout_5 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_5.scrollable = false;
			verticalLayout_5.distribution = "center";
			verticalLayout_5.spacing = 0;
			verticalLayout_5.topMargin = 64;
			verticalLayout_5.bottomMargin = 0;
			group_8.setLayout(verticalLayout_5);
			(function(container){
				var group_9 = new cpr.controls.Container();
				group_9.style.setClasses(["welfare-service-tab-group"]);
				// Layout
				var verticalLayout_6 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_6.distribution = "center";
				verticalLayout_6.spacing = 0;
				group_9.setLayout(verticalLayout_6);
				(function(container){
					var group_10 = new cpr.controls.Container();
					group_10.style.setClasses(["welfare-service-tab-group"]);
					// Layout
					var flowLayout_3 = new cpr.controls.layouts.FlowLayout();
					flowLayout_3.scrollable = false;
					flowLayout_3.horizontalSpacing = 0;
					flowLayout_3.verticalSpacing = 0;
					flowLayout_3.lineWrap = false;
					group_10.setLayout(flowLayout_3);
					(function(container){
						var radioButton_1 = new cpr.controls.RadioButton("rdb1");
						radioButton_1.value = "service";
						radioButton_1.fixedWidth = 195;
						radioButton_1.itemSpacing = 0;
						radioButton_1.style.setClasses(["welfare-service-tab-header"]);
						(function(radioButton_1){
							radioButton_1.addItem(new cpr.controls.Item("복지서비스", "service"));
							radioButton_1.addItem(new cpr.controls.Item("서비스신청", "application"));
							radioButton_1.addItem(new cpr.controls.Item("복지지갑", "wallet"));
						})(radioButton_1);
						container.addChild(radioButton_1, {
							"autoSize": "width",
							"width": "585px",
							"height": "62px"
						});
						var group_11 = new cpr.controls.Container();
						group_11.style.setClasses(["welfare-service-all"]);
						// Layout
						var flowLayout_4 = new cpr.controls.layouts.FlowLayout();
						flowLayout_4.scrollable = false;
						flowLayout_4.horizontalSpacing = 0;
						flowLayout_4.verticalSpacing = 0;
						flowLayout_4.horizontalAlign = "right";
						flowLayout_4.lineWrap = false;
						flowLayout_4.topMargin = 25;
						group_11.setLayout(flowLayout_4);
						(function(container){
							var button_13 = new cpr.controls.Button();
							button_13.value = "복지서비스 전체보기";
							button_13.icon = "../theme/images/com/main/das/ico_arrow_right.png";
							button_13.iconAlign = "right";
							button_13.style.setClasses(["btn-welfare-service-all", "btn-transparent"]);
							container.addChild(button_13, {
								"autoSize": "width",
								"width": "165px",
								"height": "20px"
							});
							var button_14 = new cpr.controls.Button();
							button_14.visible = false;
							button_14.value = "서비스신청 바로가기";
							button_14.icon = "../theme/images/com/main/das/ico_arrow_right.png";
							button_14.iconAlign = "right";
							button_14.style.setClasses(["btn-welfare-service-all", "btn-transparent"]);
							container.addChild(button_14, {
								"autoSize": "width",
								"width": "165px",
								"height": "20px"
							});
							var button_15 = new cpr.controls.Button();
							button_15.visible = false;
							button_15.value = "지갑 바로가기";
							button_15.icon = "../theme/images/com/main/das/ico_arrow_right.png";
							button_15.iconAlign = "right";
							button_15.style.setClasses(["btn-welfare-service-all", "btn-transparent"]);
							container.addChild(button_15, {
								"autoSize": "width",
								"width": "165px",
								"height": "20px"
							});
						})(group_11);
						container.addChild(group_11, {
							"width": "calc(100% - 591px)",
							"height": "62px"
						});
					})(group_10);
					container.addChild(group_10, {
						"width": "1217px",
						"height": "62px"
					});
					var tabFolder_1 = new cpr.controls.TabFolder();
					tabFolder_1.hideHeader = true;
					tabFolder_1.headerArrowPosition = "none";
					tabFolder_1.itemSizing = "fixed";
					tabFolder_1.preferredItemWidth = 195;
					tabFolder_1.style.setClasses(["welfare-service-tab"]);
					
					var tabItem_1 = (function(tabFolder){
						var tabItem_1 = new cpr.controls.TabItem();
						tabItem_1.text = "복지서비스";
						tabItem_1.name = "service";
						var group_12 = new cpr.controls.Container("grp1");
						group_12.style.setClasses(["tab-cont-01"]);
						// Layout
						var verticalLayout_7 = new cpr.controls.layouts.VerticalLayout();
						verticalLayout_7.spacing = 0;
						verticalLayout_7.topMargin = 46;
						verticalLayout_7.bottomMargin = 55;
						group_12.setLayout(verticalLayout_7);
						(function(container){
							var group_13 = new cpr.controls.Container("grp2");
							group_13.clipContent = false;
							group_13.style.setClasses(["welfare-service-tags"]);
							group_13.style.css({
								"background-color" : "red"
							});
							// Layout
							var flowLayout_5 = new cpr.controls.layouts.FlowLayout();
							flowLayout_5.scrollable = false;
							flowLayout_5.horizontalSpacing = 10;
							flowLayout_5.verticalSpacing = 10;
							flowLayout_5.lineWrap = false;
							group_13.setLayout(flowLayout_5);
							(function(container){
								var radioButton_2 = new cpr.controls.RadioButton("rdb2");
								radioButton_2.value = "value2";
								radioButton_2.fixedWidth = false;
								radioButton_2.itemSpacing = 6;
								radioButton_2.style.setClasses(["welfare-service-tag"]);
								radioButton_2.style.css({
									"background-color" : "blue"
								});
								(function(radioButton_2){
									radioButton_2.addItem(new cpr.controls.Item("# 임신·출산", "value1"));
									radioButton_2.addItem(new cpr.controls.Item("# 영유아", "value2"));
									radioButton_2.addItem(new cpr.controls.Item("# 아동·청소년", "value3"));
									radioButton_2.addItem(new cpr.controls.Item("# 노년", "value4"));
									radioButton_2.addItem(new cpr.controls.Item("# 장애인", "value5"));
								})(radioButton_2);
								container.addChild(radioButton_2, {
									"autoSize": "width",
									"width": "647px",
									"height": "40px"
								});
							})(group_13);
							container.addChild(group_13, {
								"width": "400px",
								"height": "40px"
							});
							var group_14 = new cpr.controls.Container("grp3");
							// Layout
							var flowLayout_6 = new cpr.controls.layouts.FlowLayout();
							flowLayout_6.scrollable = false;
							flowLayout_6.horizontalSpacing = 0;
							flowLayout_6.verticalSpacing = 0;
							flowLayout_6.lineWrap = false;
							group_14.setLayout(flowLayout_6);
							(function(container){
								var button_16 = new cpr.controls.Button("btn1");
								button_16.value = "Button";
								container.addChild(button_16, {
									"width": "100px",
									"height": "260px"
								});
								var group_15 = new cpr.controls.Container("grp4");
								group_15.style.setClasses(["slide-box"]);
								// Layout
								var verticalLayout_8 = new cpr.controls.layouts.VerticalLayout();
								verticalLayout_8.distribution = "leading";
								verticalLayout_8.spacing = 0;
								verticalLayout_8.leftMargin = 30;
								verticalLayout_8.rightMargin = 30;
								verticalLayout_8.topMargin = 30;
								verticalLayout_8.bottomMargin = 30;
								group_15.setLayout(verticalLayout_8);
								(function(container){
									var group_16 = new cpr.controls.Container("grp5");
									group_16.style.setClasses(["related-tags"]);
									// Layout
									var flowLayout_7 = new cpr.controls.layouts.FlowLayout();
									flowLayout_7.scrollable = false;
									flowLayout_7.horizontalSpacing = 6;
									flowLayout_7.verticalSpacing = 6;
									flowLayout_7.lineWrap = false;
									group_16.setLayout(flowLayout_7);
									(function(container){
										var output_6 = new cpr.controls.Output("opt1");
										output_6.value = "# 영유아";
										container.addChild(output_6, {
											"autoSize": "width",
											"width": "100px",
											"height": "30px"
										});
										var output_7 = new cpr.controls.Output("opt2");
										output_7.value = "# 중앙부처";
										container.addChild(output_7, {
											"autoSize": "width",
											"width": "100px",
											"height": "30px"
										});
									})(group_16);
									container.addChild(group_16, {
										"width": "100%",
										"height": "30px"
									});
									var group_17 = new cpr.controls.Container("grp6");
									// Layout
									var verticalLayout_9 = new cpr.controls.layouts.VerticalLayout();
									verticalLayout_9.spacing = 16;
									verticalLayout_9.topMargin = 24;
									verticalLayout_9.bottomMargin = 42;
									group_17.setLayout(verticalLayout_9);
									(function(container){
										var output_8 = new cpr.controls.Output("opt3");
										output_8.value = "보육료 지원";
										container.addChild(output_8, {
											"autoSize": "height",
											"width": "100px",
											"height": "20px"
										});
										var output_9 = new cpr.controls.Output("opt4");
										output_9.value = "만 0세 ~ 5세 어린이집을 이용하는 영유아가구의 보육료 등을 지원";
										container.addChild(output_9, {
											"autoSize": "height",
											"width": "100px",
											"height": "20px"
										});
									})(group_17);
									container.addChild(group_17, {
										"autoSize": "height",
										"width": "100%",
										"height": "122px"
									});
									var button_17 = new cpr.controls.Button("btn2");
									button_17.value = "자세히 보기";
									container.addChild(button_17, {
										"width": "100px",
										"height": "23px"
									});
								})(group_15);
								container.addChild(group_15, {
									"autoSize": "none",
									"width": "400px",
									"height": "260px"
								});
							})(group_14);
							container.addChild(group_14, {
								"autoSize": "none",
								"width": "400px",
								"height": "260px"
							});
						})(group_12);
						tabItem_1.content = group_12;
						return tabItem_1;
					})(tabFolder_1);
					tabFolder_1.addTabItem(tabItem_1);
					
					var tabItem_2 = (function(tabFolder){
						var tabItem_2 = new cpr.controls.TabItem();
						tabItem_2.text = "서비스신청";
						tabItem_2.name = "application";
						var group_18 = new cpr.controls.Container("grp7");
						group_18.style.setClasses(["tab-cont-02"]);
						// Layout
						var verticalLayout_10 = new cpr.controls.layouts.VerticalLayout();
						group_18.setLayout(verticalLayout_10);
						(function(container){
						})(group_18);
						tabItem_2.content = group_18;
						return tabItem_2;
					})(tabFolder_1);
					tabFolder_1.addTabItem(tabItem_2);
					
					var tabItem_3 = (function(tabFolder){
						var tabItem_3 = new cpr.controls.TabItem();
						tabItem_3.text = "복지지갑";
						tabItem_3.name = "wallet";
						var group_19 = new cpr.controls.Container("grp8");
						group_19.style.setClasses(["tab-cont-03"]);
						// Layout
						var verticalLayout_11 = new cpr.controls.layouts.VerticalLayout();
						group_19.setLayout(verticalLayout_11);
						(function(container){
						})(group_19);
						tabItem_3.content = group_19;
						return tabItem_3;
					})(tabFolder_1);
					tabFolder_1.addTabItem(tabItem_3);
					tabFolder_1.setSelectedTabItem(tabItem_1);
					container.addChild(tabFolder_1, {
						"autoSize": "height",
						"width": "1217px",
						"height": "526px"
					});
				})(group_9);
				container.addChild(group_9, {
					"autoSize": "height",
					"width": "1217px",
					"height": "588px"
				});
			})(group_8);
			container.addChild(group_8, {
				"autoSize": "height",
				"width": "100%",
				"height": "590px"
			});
		}
	});
	app.title = "Dashboard";
	cpr.core.Platform.INSTANCE.register(app);
})();
