/*
 * App URI: 202007/dialogSample
 * Source Location: 202007/dialogSample.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("202007/dialogSample", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * dialogSample.js
			 * Created at 2020. 7. 23. 오후 4:40:54.
			 *
			 * @author han
			 ************************************************/
			
			var util = createCommonUtil();
			
			/*
			 * "Button" 버튼(btn1)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var btn1 = e.control;
				
				
			//	app.openDialog("202007/dialogs", {width : 200, height : 80}, function(dialog){
			//		dialog.ready(function(dialogApp){
			//			// 필요한 경우, 다이얼로그의 앱이 초기화 된 후, 앱 속성을 전달하십시오.
			//			dialog.style.header.css({"background-color" :"red"});				
			//			
			//			dialog.initValue = {
			//				"opts" : app.lookup("ipb1").value
			//			}
			//			
			//		});
			//		dialog.headerTitle = "HELLO";
			//		dialog.style.header.css({"background-color" : "red"});
			//	}).then(function(returnValue){
			//		;
			//	});
			//	util.Dialog.open(app, "202007/dialogs", 150, 80, function(ev){}, {},{
			//		readyFunction : function(/*cpr.controls.Dialog*/dialog) {
			//			
			//			dialog.style.header.css({"background-color" : "red"});
			//		},
			//		headerTitle : "키호호호호"
			//	});
			
			//	app.openDialog("202007/dialogs", {width : 150, height : 80}, function(dialog){
			//		dialog.ready(function(dialogApp){
			////			dialogApp.name = "asdasd";
			//			dialog.name = "202007/dialogs";
			//			dialog.initValue = {
			//				"dias" : dialog
			//			};
			//			// 필요한 경우, 다이얼로그의 앱이 초기화 된 후, 앱 속성을 전달하십시오.
			//		});
			//	}).then(function(returnValue){
			//		;
			//	});
				app.dialogManager.openDialog("202007/dialogs", "202007/dialogs");
			/**
			 * 
			 * @param {cpr.controls.Dialog} dialog
			 */
			function abc(dialog){
			}
			
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var inputBox_1 = new cpr.controls.InputBox("ipb1");
			container.addChild(inputBox_1, {
				"top": "82px",
				"left": "20px",
				"width": "535px",
				"height": "20px"
			});
			
			var button_1 = new cpr.controls.Button("btn1");
			button_1.value = "Button";
			if(typeof onBtn1Click == "function") {
				button_1.addEventListener("click", onBtn1Click);
			}
			container.addChild(button_1, {
				"top": "112px",
				"left": "20px",
				"width": "100px",
				"height": "20px"
			});
		}
	});
	app.title = "dialogSample";
	cpr.core.Platform.INSTANCE.register(app);
})();
