/*
 * App URI: 202008/tabTest
 * Source Location: 202008/tabTest.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("202008/tabTest", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * tabTest.js
			 * Created at 2020. 8. 12. 오전 10:07:21.
			 *
			 * @author han
			 ************************************************/
			
			/**
			 * 외부에서 mdi폴더에 앱아이템을 추가하기 위해 만들어진 함수입니다.
			 * @param {#app} appId
			 * @param {(item: cpr.controls.TabItem, app: cpr.core.App)=>Void} appLoadCompleteCallback
			 */
			exports.addTabItemFromOutside = function(appId,appLoadCompleteCallback){
				var vcMdiFolder = app.lookup("mdi1");
				
				vcMdiFolder.addItemWithApp(appId,true,appLoadCompleteCallback);
			}
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var mDIFolder_1 = new cpr.controls.MDIFolder("mdi1");
			
			var tabItem_1 = (function(tabFolder){
				var tabItem_1 = new cpr.controls.TabItem();
				tabItem_1.text = "tab1";
				var embeddedApp_1 = new cpr.controls.EmbeddedApp("ea1");
				cpr.core.App.load("202008/tab1", function(app) {
					if(app){
						embeddedApp_1.app = app;
					}
				});
				tabItem_1.content = embeddedApp_1;
				return tabItem_1;
			})(mDIFolder_1);
			mDIFolder_1.addTabItem(tabItem_1);
			mDIFolder_1.setSelectedTabItem(tabItem_1);
			container.addChild(mDIFolder_1, {
				"top": "50px",
				"right": "0px",
				"bottom": "60px",
				"left": "0px"
			});
		}
	});
	app.title = "tabTest";
	cpr.core.Platform.INSTANCE.register(app);
})();
