/*
 * App URI: 202010/verticalTest
 * Source Location: 202010/verticalTest.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("202010/verticalTest", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * verticalTest.js
			 * Created at 2020. 10. 5. 오후 5:26:27.
			 *
			 * @author HANS
			 ************************************************/
			
			
			
			/*
			 * 그리드에서 filterdialog-open 이벤트 발생 시 호출.
			 * 필터팝업을 열때 발생하는 이벤트.
			 */
			function onGrd1FilterdialogOpen(/* cpr.events.CGridEvent */ e){
				/** 
				 * @type cpr.controls.Grid
				 */
				var grd1 = e.control;
				
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("ds1");
			dataSet_1.parseData({
				"columns": [
					{"name": "label"},
					{"name": "value"},
					{"name": "parent"}
				],
				"rows": [
					{"label": "label1", "value": "1", "parent": ""},
					{"label": "label2", "value": "value2", "parent": "1"},
					{"label": "label3", "value": "value3", "parent": "1"},
					{"label": "label4", "value": "value4", "parent": "1"},
					{"label": "label5", "value": "value5", "parent": "1"},
					{"label": "label6", "value": "value6", "parent": "1"},
					{"label": "label7", "value": "value7", "parent": "1"},
					{"label": "label8", "value": "value8", "parent": "1"},
					{"label": "label9", "value": "value9", "parent": "1"},
					{"label": "label10", "value": "value10", "parent": "1"},
					{"label": "label11", "value": "value11", "parent": "1"},
					{"label": "label12", "value": "value12", "parent": "1"}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var grid_1 = new cpr.controls.Grid("grd1");
			grid_1.init({
				"dataSet": app.lookup("ds1"),
				"columns": [
					{"width": "100px"},
					{"width": "100px"},
					{"width": "100px"}
				],
				"header": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.targetColumnName = "label";
								cell.filterable = true;
								cell.sortable = false;
								cell.text = "label";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.targetColumnName = "value";
								cell.filterable = true;
								cell.sortable = false;
								cell.text = "value";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.targetColumnName = "parent";
								cell.filterable = true;
								cell.sortable = false;
								cell.text = "parent";
							}
						}
					]
				},
				"detail": {
					"rows": [{"height": "24px"}],
					"cells": [
						{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.columnName = "label";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 1},
							"configurator": function(cell){
								cell.columnName = "value";
							}
						},
						{
							"constraint": {"rowIndex": 0, "colIndex": 2},
							"configurator": function(cell){
								cell.columnName = "parent";
							}
						}
					]
				}
			});
			if(typeof onGrd1FilterdialogOpen == "function") {
				grid_1.addEventListener("filterdialog-open", onGrd1FilterdialogOpen);
			}
			container.addChild(grid_1, {
				"top": "20px",
				"left": "20px",
				"width": "400px",
				"height": "200px"
			});
		}
	});
	app.title = "verticalTest";
	cpr.core.Platform.INSTANCE.register(app);
})();
